soimort/you-get

- src/you_get/processor/join_mp4.py
modified:   src/you_get/processor/join_mp4.py
You can try with some video from qq, such as 
http://v.qq.com/cover/x/xex6po9q55akzsr.html
The first slice has udat issue, and the 20th slice has sample count issue
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/466)
> Support skipping udta box, and ignore samples > 1

- src/you_get/extractors/bilibili.py
Can not find sina_download_by_id in source, it may typo of sina_download_by_vid
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/476)
> maybe typo

- src/you_get/extractors/iqiyi.py
may have differnet links type. =.=wait for more research.
for #486 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/487)
> quick fix iqiyi

- src/you_get/extractors/bilibili.py
- src/you_get/extractors/sohu.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/489)
> fix bilibili and bug #353

- src/you_get/processor/ffmpeg.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/496)
> escape filenames for ffmpeg concatenating

- src/you_get/extractors/xiami.py
about b61e995f9228ef629e51bd4be4225ea473699dcf
update showcollect url as described in issue #502 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/503)
> Xiami: update collect url; fix #502

- src/you_get/extractors/iqiyi.py
Fix for #519 
add changelog in iqiyi.py for others checking iqiyi player swf version.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/520)
> iqiyi changes its encrypt key

- src/you_get/common.py
- src/you_get/extractors/facebook.py
- src/you_get/extractors/vidto.py
Previously would throw error if there is no hd_src
Modified to use json parser and check if hd_src is None
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/514)
> Fix facebook extractor

- src/you_get/extractors/bilibili.py
for #521
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/522)
> bilibili title from h2 to h1

- src/you_get/extractors/iqiyi.py
iQiyi changes it's swf version frequently,so enc key changes too.
So before downloading,get swf from video page and extract the key.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/523)
> now get iqiyi enc key automatically

- src/you_get/extractors/netease.py
This occurs for example with these urls:
http://music.163.com/song?id=17699228
http://music.163.com/song?id=17699232
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/536)
> Fix case when hMusic data is None

- src/you_get/extractors/netease.py
http://music.163.com/#/song/30706076/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/533)
> netease: more url pattern

- src/you_get/extractors/acfun.py
- src/you_get/extractors/letv.py
#528 will not fix the problem, since the old API is down.
Sorry for that drama, did not have enough energy to go through all the test cases.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/534)
> Fix Acfun, add uu to Letvcloud, update key(fix #530, #495,#525, #528)

- src/you_get/extractors/iqiyi.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/543)
> fix for iqiyi new encrypt method, for #542

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/twitter.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/545)
> Add support for Twitter

- src/you_get/extractor/acfun.py
- src/you_get/extractor/qq.py
使用了@lvqier  https://github.com/lvqier/crawlers/blob/master/txsp/txsp.py 的算法来解析，将其从p2移植到p3
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/470)
> fix qq support

- src/you_get/common.py
- src/you_get/extractors/zhanqi.py
- src/you_get/processor/join_ts.py
Zhanqi extractor works again...
And added ts merging implementation...
Signed-off-by: liushuyu <liushuyu_011@163.com>
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/546)
> Fix zhanqi

- src/you_get/extractors/iqiyi.py
for #549 .
God damn iqiyi.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/550)
> iqiyi new key

- src/you_get/extractors/yinyuetai.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/557)
> sometimes there's some parameters,drop it

- src/you_get/extractors/iqiyi.py
new key
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/562)
> fix iqiyi(20150703)

- src/you_get/__main__.py
- src/you_get/extractors/netease.py
example url: http://music.163.com/#/mv?id=440007
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/574)
> [netease] support for mv urls

- src/you_get/common.py
- src/you_get/extractors/netease.py
e.g. http://163.fm/LzbHaQN
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/584)
> [netease] support for 163.fm short url

- src/you_get/extractors/iqiyi.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/589)
> update key for iqiyi,thanks to @Freshman585

- src/you_get/extractors/iqiyi.py
for http://www.iqiyi.com/common/flashplayer/20150805/MainPlayer_5_2_26_c3_3_7.swf
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/591)
> new iqiyi key

- src/you_get/extractors/iqiyi.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/593)
> [iqiyi] update key

- src/you_get/extractors/iqiyi.py
Fix iqiyi 1080p parse.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/597)
>  [iqiyi] fix 1080p parse by set um=1

- src/you_get/extractors/iqiyi.py
issue #602 
3cba91f1453145438ac5e4f5983bc086
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/603)
> fix iqiyi(20150820)

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/miaopai.py
Something like this.
I did not use the M3U file, but the mobile version instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/605)
> Add Weibo Miaopai support(微博秒拍视频)

- src/you_get/extractors/tudou.py
测试地址： http://www.tudou.com/programs/view/bRZga7Qrxlw/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/613)
> fix bug in tudou, fix #612

- src/you_get/extractors/dailymotion.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/614)
> fix dailymotion for #609

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/funshion.py
This should do.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/619)
> Add funshion support, fix #215, replace #601, #604

- src/you_get/common.py
- src/you_get/extractors/embed.py
- src/you_get/extractors/youku.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/621)
> support embed player for youku/tudou

- src/you_get/extractors/iqiyi.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/630)
> rewrit iqiyi using VideoExtractor class

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/metacafe.py
Test:
```
$ python3 you-get http://www.metacafe.com/watch/10859352/angelina_jolie_wows_in_low_cut_camisole_in_hawaii_after_mastectomy/
Video Site: metacafe
Title:      Angelina Jolie Wows in Low-Cut Camisole in Hawaii After Mastectomy
Size:       7.73 MiB (8104213 Bytes)
Downloading Angelina Jolie Wows in Low-Cut Camisole in Hawaii After Mastectomy.mp4 ...
16.2% (  1.2/7.7  MB) [=======                                 ] 1/1
```
Also fix readme's "/" issue by myself.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/620)
> Add metacafe support, fix #83

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/iqilu.py
齐撸网（
```
python3 you-get http://v.iqilu.com/zypd/wsdmx/2015/0910/4257508.html
Video Site: iQilu
Title:      我是大明星：湖南愣妹子暴虐山东评委 唇枪舌战后敏健被“逼疯”
Size:       63.86 MiB (66961720 Bytes)
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/636)
> Add iQilu support (齐鲁网，山东网络台)

- src/you_get/common.py
Current logic of skipping download when file already exists have some bugs when working together with ffmpeg-merge.
TL;DR: When merging multi parts using ffmpeg, we change the ext name of the output file. Thus messed up with the current skipping download mechanism.
Considering a video with title "TITLE", it have multiple parts, all with ext ".flv".
We will look for "TITLE.flv" first. If it doesn't exist, we will download all parts as "TITLE[00].flv", "TITLE[01].flv"... etc.
Then if we don't have ffmpeg installed, we merged them into "TITLE.flv".
So far so good.
But problem happens if we have ffmpeg installed. We will merge all parts to "TITLE.mp4". That means when we try to download the same video again, it will not be able to find any file named "TITLE.flv". Thus it will download again. …
> [common] fix skipping download of file existence in some cases

- src/you_get/extractors/iqiyi.py
fix #653 
thanks to #617
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/655)
> [IQIYI] 2015/09/18 new salt,describe method in comments of iqiyi.py

- src/you_get/extractors/qq.py
Let's drop the old overbloated (and slow) implementation and take a new approach. (as suggested by #657)
Tested on:
- http://v.qq.com/boke/page/k/0/4/k0164r62z74.html
- http://v.qq.com/boke/page/t/0/t/t0164hackqt.html
- http://v.qq.com/boke/page/y/0/f/y0156esn97f.html (#548)
- http://v.qq.com/cover/v/vg7oiucmb3vp2t3.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/658)
> Rewrite implementation for QQ

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/archive.py
Tested on:
- https://archive.org/details/ssfWhitent1
- https://archive.org/details/AndyWarhol.Eat.1963
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/660)
> Add support for Internet Archive

- src/you_get/extractors/iqiyi.py
Closes #664
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/667)
> [iqiyi] Update enc and authkey

- src/you_get/extractors/iqiyi.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/669)
>  [iqiyi] simplify mix() function

- src/you_get/common.py
- src/you_get/extractor.py
- src/you_get/json_output.py
Add an option `--json` to output video information in json text. 
It works with extractors use `VideoExtractor`. 
Example
```
$ ./you-get --json "http://www.iqiyi.com/v_19rrobguj0.html"
{
"site": "爱奇艺 (Iqiyi)",
"streams": {
"fullhd": {
"container": "f4v",
"size": 970278781,
"src": [
"http://60.165.44.223/videos/v0/20150921/c8/ce/b6112205757213cdaacec4ef2c772662.f4v?key=0a8ab224fcadd30507aad780cdc27daee&src=iqiyi.com&su=c02d4f772a644ce98194ab91f8772555&qyid=7088c4d3ac8f4aa1bfe8087502e7d402&client=&z=&bt=&ct=&tn=12016&uuid=dcab5d63-5603c477-2",
"http://60.165.44.210/videos/v0/20150921/c8/ce/fb678efffc4d9495b2edd391763d1a31.f4v?key=0c1205d3a7548b478e42cb288269535cc&src=iqiyi.com&su=c02d4f772a644ce98194ab91f8772555&qyid=567135417fc34c859449987285a2112a&client=&z=&bt=&ct=&tn=16620&uuid=dcab5d63 …
```
>  add --json option: output video information in json text

- src/you_get/common.py
- src/you_get/json_output.py
Now more extractors not written with `VideoExtractor` can support `--json` option. 
Examples: 
```
$ ./you-get --json "http://v.pptv.com/show/ORXicfeVLuiclc2kI.html"
{
"site": "PPTV.com",
"streams": {
"__default__": {
"container": "mp4",
"size": 192001265,
"src": [
"http://ccf.pptv.com/0/dacae18b9685bc353b0f6acf21ed36a0.mp4?key=bc2dc77f18ce32d849807813216059ed&fpp.ver=1.3.0.4&k=209bd78a25dc51e19cdcf749f11d1ffd-828d-1443278382&type=web.fpp",
"http://ccf.pptv.com/1/dacae18b9685bc353b0f6acf21ed36a0.mp4?key=bc2dc77f18ce32d849807813216059ed&fpp.ver=1.3.0.4&k=209bd78a25dc51e19cdcf749f11d1ffd-828d-1443278382&type=web.fpp",
"http://ccf.pptv.com/2/dacae18b9685bc353b0f6acf21ed36a0.mp4?key=bc2dc77f18ce32d849807813216059ed&fpp.ver=1.3.0.4&k=209bd78a25dc51e19cdcf749f11d1ffd-828d-1443278382&type=web.fpp …
```
>  --json option now can support more extractors not using VideoExtractor

- src/you_get/extractors/sina.py
fix for http://video.sina.com.cn/view/249851143.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/691)
> [sina] match vid from the page

- src/you_get/extractors/tudou.py
Apparently `you-get -l` is broken for Tudou playlists.
* http://www.tudou.com/plcover/esY05WLzWfo/
* http://www.tudou.com/listplay/esY05WLzWfo/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/698)
> [Tudou] Fix playlist support

- README.md
- src/you_get/common.py
- src/you_get/extractor.py
- src/you_get/extractors/youtube.py
- src/you_get/processor/ffmpeg.py
Support YouTube videos of 1080p or even higher qualities.
(Fix #395, #599)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/704)
> [YouTube] Support DASH videos

- src/you_get/extractors/yinyuetai.py
Examples:
* http://v.yinyuetai.com/playlist/3113497
* http://v.yinyuetai.com/playlist/1579789
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/706)
> [YinYueTai] Playlist support

- src/you_get/extractors/netease.py
Examples:
* http://music.163.com/#/song?id=732868
* http://music.163.com/#/song?id=28196351
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/709)
> [163] Download lyrics in LRC format

- src/you_get/extractors/youtube.py
Follow-up of #704 .
VEVO videos require encrypted signatures for DASH streaming. They may not be accessed via `dashmpd`.
Examples:
* https://www.youtube.com/watch?v=CWFUwdaT8kM
* https://www.youtube.com/watch?v=_HUVPglTfNY
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/710)
> [YouTube] Download DASH streams for VEVO videos

- src/you_get/common.py
- src/you_get/extractors/baidu.py
- src/you_get/extractors/flickr.py
- src/you_get/extractors/google.py
- src/you_get/extractors/instagram.py
- src/you_get/extractors/nanagogo.py
- src/you_get/extractors/tumblr.py
- src/you_get/extractors/twitter.py
- src/you_get/extractors/universal.py
- src/you_get/processor/rtmpdump.py
Download photos (in case no video found) from:
Test links:
- https://www.flickr.com/photos/soimort/19719408938
Test links:
- https://plus.google.com/105078910574942856246/posts/9DShrZy5c5W
Test links:
- https://instagram.com/p/85bwuykCm2/
Test links:
- http://voz48reloaded.tumblr.com/post/129885117086/matsuoka-natsumi-1st-photobook-tsuishin
Test links:
- https://twitter.com/EXtaishu/status/644051111729467392
Test links:
- http://7gogo.jp/iwatate-saho/5126
Test links:
- http://tieba.baidu.com/p/4113358496#!/l/p1
- http://tieba.baidu.com/p/4111338484
Test links:
- http://microblog.soimort.org/post/92438462120/%E6%9C%A8%E5%B4%8E%E3%82%86%E3%82%8A%E3%81%82%EF%BD%81%EF%BD%8B%EF%BD%82%EF%BC%94%EF%BC%98%E5%83%95%E3%81%AE%E3%82%B0%E3%83%AC%E3%82%A4%E3%83%88%E3%81%AA%E5%BD%BC%E5%A5%B3
- …
> Image downloader

- src/you_get/extractors/miomio.py
Not something very hard.
But I do worry that whether Miomio can make it...
```
python3 you-get -i http://www.miomio.tv/watch/cc244886/
Site:       MioMio.tv
Title:      单机恐怖解密惩罚者杰克实况娱乐解说第十三期  神秘的幽灵 
Size:       430.49 MiB (451406274 Bytes)
python3 you-get -i http://www.miomio.tv/watch/cc244732/
Site:       MioMio.tv
Title:      劇場霊からの招待状　第2話 - 15 10 19
Size:       180.09 MiB (188841439 Bytes)
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/721)
> [miomio] quick fix #716

- src/you_get/common.py
This works as expected:
```
$ you-get -i BOOM-HAH-BOOM-HAH-HAH
```
Drop the `-i` and just download the best match to your collections:
```
$ you-get "Girls, Girls, Girls"
```
And straight to your ears:
```
$ you-get -p chromium 'Merzbow Pulse Demon'
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/723)
> Do a Google search

- src/you_get/extractors/youtube.py
As suggested in a comment https://github.com/soimort/you-get/issues/720#issuecomment-149799424
```
λ  you-get-develop [develop] you-get --debug https://www.youtube.com/watch?v=dwnppvrPYVs
you-get: [Failed] "Uploaderen har ikke gjort denne video tilgængelig i dit land."
you-get: version 0.4.100
you-get: ['https://www.youtube.com/watch?v=dwnppvrPYVs']
```
```
λ  you-get-develop [develop] you-get --debug https://www.youtube.com/watch?v=z3Lfa7dQXh4 
you-get: [Failed] "Advarsel om indhold"
you-get: version 0.4.100
you-get: ['https://www.youtube.com/watch?v=z3Lfa7dQXh4']
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/730)
> [YouTube] Show error message when a video is unavailable

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/interest.py
```
python3 you-get --debug http://ch.interest.me/zhtv/VOD/View/114789
Site:       interest.me
Title:      무더기 유골을 발견하다
Size:       0.0 MiB (0 Bytes)
Call rtmpdump:
rtmpdump -r rtmp://zhtv.cjenm.skcdn.com/zhtv/_definst_/41A6FE202E89B98555DC5E5C123D967E6E90032F2C5904BA58A79B121A7172F1D378A1A43949F78F67D91A3CAD3FF4653C4A011F98AE9B491008D20B5F4DC2EBD0CABB36B721D5EDD3FF935AA778D893 -o ./무더기 유골을 발견하다.mp4
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
^CCaught signal: 2, cleaning up, just a second...
ERROR: RTMP_Connect0, failed to connect socket. 4 (Interrupted system call)
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
> [interest.me] Add Interest.me support

- .gitignore
- Makefile
- README.md
- README.rst
- setup.py
- src/you_get/util/git.py
- src/you_get/version.py
Thanks to everyone who has ever contributed to `you-get`. Time for a new minor release now.
(the release was scheduled a week ago, with a few patches on interesting features I want, somehow it took a bit longer than expected)
It's a lot of commits (100+). If you want to get a quick overview of new features that have been added, take a look at #703, #704, #705, #706, #707, #708, #709, #710, #711, #712, #717, #719, #723, #730, #732. Also, grok the list of all relevant commits: https://github.com/soimort/you-get/compare/v0.3.36...0.4
There won't be a changelog to document and credit every improvement we made, because
If you don't care about the actual code, just visit our website https://you-get.org/ and read the new user manual (will be online later today)
The issue page …
> Release 0.4.x

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/dilidili.py
```
python3 you-get   --debug  http://www.dilidili.com/watch/9901/
Site:       dilidili
Title:      钢之炼金术师 FULLMETAL ALCHEMIST 第1话「钢之炼金术师」
Size:       180.35 MiB (189109341 Bytes)
Downloading 钢之炼金术师 FULLMETAL ALCHEMIST 第1话「钢之炼金术师」.mp4 ...
```
I've prepared ```stream_types``` for following developing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/737)
> [dilidili] Add support

- src/you_get/common.py
- src/you_get/version.py
Starting from version **[0.4.136](https://github.com/soimort/you-get/releases/tag/v0.4.136)**, we will ship Windows binaries for every release of `you-get`, as I promised.
Those binaries were built with [PyInstaller](https://github.com/pyinstaller/pyinstaller), so no more Python installation is required. The download [you-get-0.4.136-win32.exe](https://github.com/soimort/you-get/releases/download/v0.4.136/you-get-0.4.136-win32.exe) is a standalone executable of `you-get`; the download [you-get-0.4.136-win32-full.7z](https://github.com/soimort/you-get/releases/download/v0.4.136/you-get-0.4.136-win32-full.7z) also contains ffmpeg and rtmpdump for convenience. If you are already using ffmpeg on Windows, you just need the `exe` file; otherwise, use the `7z` package.
Of course we don't have a …
> Windows build

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/pinterest.py
As requested in #744.
At this point, the usage of `VideoExtractor` was limited on just a few sites: **YouTube**, **Youku**, and **IQiyi**. All of them are non-trivial to implement; and relevant code is hard to read. As I understood, this has been a major obstacle for starters who wish to implement new extractors using `VideoExtractor`.
I implemented the code for extracting images from **Pinterest**, as a showcase of using `VideoExtractor` - it's all in some 50 lines of code, well commented and easy to make sense for anyone (hopefully).
It seems I'm unlikely to refactor this part for at least a while. So, you may use [`pinterest.py`](https://github.com/soimort/you-get/blob/f44a99536680c3d6529a28cf0f10ce09f2f86279/src/you_get/extractors/pinterest.py) here in this PR as a minimal boilerplate …
> Add support for Pinterest, as a showcase of using VideoExtractor

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/musicplayon.py
Using `VideoExtractor`.
Example links:
* http://en.musicplayon.com/play?v=166605
* http://en.musicplayon.com/play?v=157840
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/760)
> Add support for MusicPlayOn

- src/you_get/extractors/cntv.py
添加类似于这样的URL的匹配，其中最后一段是id，http://tv.cntv.cn/video/VSET100241824133/ee5ed807346c4b6086f105ef10b559f3
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/765)
> add pattern for url 

- src/you_get/extractors/youku.py
Come from https://github.com/soimort/you-get/pull/463
fix #390 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/783)
> [Youku]Support full length of youku's video

- src/you_get/extractors/youku.py
fix #797
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/800)
> [youku]fix language bug

- src/you_get/extractors/iqiyi.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/822)
> Update iQiyi key

- src/you_get/extractors/youku.py
fix  https://github.com/soimort/you-get/pull/839  's bug
But this isn't essential.Due to yoku's change back.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/841)
> [youku]fix cookies' max-age issue

- src/you_get/extractors/youku.py
fix #845 
refer to http://www.cnblogs.com/zhxilin/p/4993074.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/847)
> [youku] fix cookie's issue

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/imgur.py
- tests/test.py
Example links:
- http://imgur.com/WVLk5nD
- http://imgur.com/gallery/EBSwb17
- http://imgur.com/a/UWkCH
```
$ ./you-get -i http://imgur.com/WVLk5nD
site:                Imgur
title:               We should have listened
- format:        original
container:     jpg
size:          0.1 MiB (80879 bytes)
- format:        thumbnail
container:     jpg
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/849)
> Add support for Imgur

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/videomega.py
Example links:
- http://videomega.tv/?ref=9r9sx4xGOGGOGx4xs9r9
- http://videomega.tv/?ref=UKRPMV8QG00GQ8VMPRKU
- http://videomega.tv/?ref=E1OMPDO446644ODPMO1E
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/850)
> Add support for Videomega

- src/you_get/extractors/zhanqi.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/862)
> fix zhanqitv

- src/you_get/extractors/youku.py
a quick fix to #875
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/876)
> [youku] fix extractor_proxy option

- src/you_get/extractors/zhanqi.py
https://github.com/soimort/you-get/issues/883
https://github.com/soimort/you-get/issues/887
> zhanqi TV now can use old algorithm, so revert recent 2 comments

- src/you_get/extractors/qq.py
e.g. http://v.qq.com/cover/p/ps6mnfqyrfo7es3.html?vid=q0181hpdvo5
hope this won't break others, or we should try to recognize the URL
pattern (maybe apply to only URLs with "/cover/")?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/896)
> [qq] fix title for some videos

- src/you_get/extractors/qq.py
e.g. http://v.qq.com/iframe/player.html?vid=q01536xb5rb&tiny=0&auto=0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/897)
> [qq] support for embedded video URLs

- src/you_get/common.py
see the commits for more info.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/898)
> Bar finetune

- src/you_get/common.py
Fix the issue mentioned here: https://github.com/soimort/you-get/pull/898#issuecomment-180113961
I haven't test with real data yet, because currently I don't have the bandwidth to do so. Please give this a try :-)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/918)
> fix bar overflows

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/thvideo.py
```
Beining$ python3 you-get --debug 'http://thvideo.tv/v/th5510#2'
Site:       THVideo
Title:      【手绘】To LOVE Ru Darkness ED的东方三魔女再现 - 比较动画
Size:       6.27 MiB (6569588 Bytes)
Downloading 【手绘】To LOVE Ru Darkness ED的东方三魔女再现 - 比较动画.mp4 ...
^C
```
They are using QiNiu for everything. Rumors said they've got some TooHows within. How terrible.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/924)
> [THVideo] Add Support

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
为了非英语用户，写个中文的。
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/935)
> [.github]Chinese translation

- src/you_get/extractors/miaopai.py
```
python3 you-get --debug 'http://video.weibo.com/show?fid=1034:b037855b1e5ff7cfb2e52714310c2b64'
Site:       miaopai
Title:      BEAUTY BEAUTY ~
Size:       9.58 MiB (10046117 Bytes)
Downloading BEAUTY BEAUTY ~.mp4 ...
0.0% (  0.0/  9.6MB) ├─────────────────────────────────────────┤[1/1] ^C
```
```
python3 you-get --debug 'http://weibo.com/p/230444b037855b1e5ff7cfb2e52714310c2b64'
Site:       miaopai
Title:      BEAUTY BEAUTY ~
Size:       9.58 MiB (10046117 Bytes)
Downloading BEAUTY BEAUTY ~.mp4 ...
0.0% (  0.0/  9.6MB) ├─────────────────────────────────────────┤[1/1] ^C
```
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/ …
> [Miaopai]Add Weibo URL pattern without login

- src/you_get/extractors/tumblr.py
Support for tumblr-hosted videos.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/942)
> Support for tumblr-hosted videos.

- .github/ISSUE_TEMPLATE.md
Ask for FAQ.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/961)
> [.github] Ask for reading FAQ

- src/you_get/extractors/__init__.py
- src/you_get/extractors/ckplayer.py
```
a = '''<ckplayer>
<flashvars>
<![CDATA[{h->3}{a->type=youku&vid=XMTQ1MzM1ODg4OA&hd=3}{defa->type=youku&vid=XMTQ1MzM1ODg4OA&hd=1|type=youku&vid=XMTQ1MzM1ODg4OA&hd=2|type=youku&vid=XMTQ1MzM1ODg4OA&hd=3}{deft->标清|高清|超清}{f->https://player.005.tv:60000/parse.php?xmlurl=null&sign=16f3bed5d02ff84405f0636a4e87971d&tmsign=c83308e383ee86afc42aae958ee9c2a8&[$pat]}]]>
</flashvars>
<info>
<title>
<![CDATA[第03话 黑之宣告]]>
</title>
<image>
<![CDATA[http://r4.ykimg.com/0541040856A1DBAE6A0A4504594527CE]]>
</image>
<duration>1435</duration>
<swf>
<![CDATA[http://player.youku.com/player.php/sid/XMTQ1MzM1ODg4OA==/v.swf]]>
</swf>
</info>
<video>
<file>
<![CDATA[http://k.youku.com/player/getFlvPath/sid/54580024759261018dd9f_00/st/flv/fileid/030001080056A1D9B53CFD1468DEFE0064593D-6938-8FF4-538B-604C83E0EC28?K=b …
```
> [CKPlayer]Extract by XML as helper

- .gitignore
- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/huaban.py
Sample link: http://huaban.com/boards/24803867/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/976)
> Add huaban.com support.

- src/you_get/extractors/youku.py
It's a quick fix for recovery to `ct=10`.Refer to #991
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/995)
> [Youku] Recover youku and fix #991

- src/you_get/processor/ffmpeg.py
As its default value was.
Fixes #1023.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1029)
> [FFmpeg] set safe option to -1

- src/you_get/common.py
- src/you_get/extractors/douyutv.py
fix to handle new domain of douyu.com (was douyutv.com)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1011)
> fix to handle new domain of douyu.com (was douyutv.com)

- src/you_get/common.py
Bypass anti-spider strategies of Pornhub.
Try this on new code:
`you-get -i http://www.pornhub.com/view_video.php?viewkey=ph56d67b6c6505e`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1053)
> [Pornhub] Add Support, Universal Solution

- README.md
Changed Badges from PNG to SVG
Also Fixed Badge Links
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1045)
> Changed Badges from PNG to SVG

- src/you_get/extractors/qq.py
fix v.qq.com 403 code
http://v.qq.com/cover/6/65d2otz0s4jhrrp.html?vid=l0020gwuwzx
> fix v.qq.com 403 code

- src/you_get/extractors/qq.py
[http://v.qq.com/page/k/9/7/k0185rbbiri.html] will redirect to [http://v.qq.com/cover/0/0gmlfifotut7c5f.html?vid=k0185rbbiri]. Add support to the previous format. Also add support to kuaibao.qq.com, e.g, http://kuaibao.qq.com/s/20160224V05DDS00.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1074)
> support for redirect URLs

- you-get
Fix issue `can't open file 'you-get': [Errno 2] No such file or directory` on OSX when run you-get with command `python3 you-get -h`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1086)
> Update file you-get change env from `python` to `python3`

- src/you_get/extractors/acfun.py
- src/you_get/extractors/youku.py
So long everyone.
I apologize for the long delay due to unexpected physical and psychological conditions.
Also I want to thank for @zhangn1985 's enlightening discussions and @soimort 's effort. Specially I give the credit to @ERioK 's POC which guided me through this patch. 
There are more people I want to thank then who I could remember. Thanks a lot.
Beining
```
$ python3 you-get -di http://www.acfun.tv/v/ac2701527
[DEBUG] get_content: http://api.aixifan.com/plays/3462634
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=CMzQyMjc0NA==
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CMzQyMjc0NA==&ct=85&sign=MXwxNDYxODIxNTAyfDI0MzZkOTYwMDNlMTIwMDRlZTg1OTRhZTAzZjI0OTc5 …
```
> Acfun: Fix Youku COOP ct85&86

- src/you_get/extractors/tudou.py
```
python3 you-get -di http://acfun.tudou.com/v/ac2702805
[DEBUG] get_content: http://api.aixifan.com/plays/3466997
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=CMzQyODc4OA==
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CMzQyODc4OA==&ct=85&sign=MXwxNDYxODIzNjY5fGNjMGEyMTVmMDk4N2ZhNDE4OWFlYTkwZDYwMWZkMDYy
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CMzQyODc4OA==&ct=86&sign=MXwxNDYxODIzNjY5fGNjMGEyMTVmMDk4N2ZhNDE4OWFlYTkwZDYwMWZkMDYy
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/94618236706658668316a_00/st/flv/fileid/03000103005720D132C04E2D9B7D2F05E66618-9F3E-9A6C-85E6-987000DD1197?token=1146&ctype=86&yxon=1&ep=Bp5ccxwBzrpHH0nA6wjcpku2X3SLmE …
```
> [Tudou]Fix acfun.tudou.com redirect, fix #695

- src/you_get/extractors/sohu.py
fix: #1098
in some case, highest video format is not valid, so just skip it, and go through to next available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1099)
> ignore invalid video format

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/mgtv.py
I have to say this is NOT WORKING, but still deserve a merged PR as the reason is the same as #1041 .
So we can just merge this then fix that one later.
POC:
```
python3 you-get --debug  --json http://www.mgtv.com/v/1/292390/c/3144453.html
[DEBUG] get_content: http://v.api.mgtv.com/player/video?video_id=3144453
[DEBUG] get_content: http://disp.titan.mgtv.com/mp4/2016/zongyi/qyjszdej_52404/A294AD700E7EA369E2030051841BC460_20160506_1_1_1122.mp4/playlist.m3u8?ver=0.1&fmt=2&pno=1000&fid=A294AD700E7EA369E2030051841BC460&gsid=82883b8574ca4fb28f4aeda52bc49ebd
[DEBUG] get_content: http://pcvideoaliyun.titan.mgtv.com/mp4/2016/zongyi/qyjszdej_52404/A294AD700E7EA369E2030051841BC460_20160506_1_1_1122.mp4/playlist.m3u8?uuid=20078732899d43fda5c266d0aac89d00&t=572d6f30&pno=1000&sign=668075c96d1d0d46a9d0f …
```
> [MangGuoTV]Add support

- src/you_get/extractors/embed.py
Added support for downloading embedded Vimeo videos.
Example URL:
- http://www.miracletutorials.com/howto-embed-vimeo/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1147)
> Support for embedded Vimeo videos

- src/you_get/extractors/__init__.py
- src/you_get/extractors/qie.py
- src/you_get/extractors/qq.py
```
$ python3 you-get --debug -i http://live.qq.com/10000814
[DEBUG] get_content: http://live.qq.com/10000814
[DEBUG] get_content: http://www.qie.tv/api/v1/room/10000814
site:                QiE （企鹅直播）
title:               台湾高中篮球联赛-圣母杯
- format:        normal
video-profile: 标清
size:          0.0 MiB (0 bytes)
- format:        middle
video-profile: 550
size:          0.0 MiB (0 bytes)
- format:        middle2
video-profile: 900
size:          0.0 MiB (0 bytes)
```
I would like to see how we can decrypt the sign of SWF player for this quick fix would not last long.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> [QiE]Add Support, close #1148

- src/you_get/extractors/ku6.py
./you-get -i --debug "http://baidu.ku6.com/watch/07457539446370454216.html?page=videoMultiNeed"
Site:       Ku6.com
Title:      英语儿歌 One,Two,Buckle My Shoe
Size:       3.34 MiB (3507248 Bytes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1164)
> Add support http://baidu.ku6.com #1163

- src/you_get/extractors/mgtv.py
This is intended to fix links like http://www.mgtv.com/v/3/168294/f/3167498.html .
Anyone in Mainland can give me more test results? Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1140)
> [MGTV]Fix some video cannot be downloaded in full length

- src/you_get/extractors/netease.py
for #1145
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1173)
> [Netease] add support for radio & program

- src/you_get/extractors/qq.py
for #1126
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1175)
> [QQ] more robust url extractor

- README.md
I think someone would like to use the latest version...
Thanks to @nuomi1 's reminder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1183)
> [Readme] Add pip install from Github

- README.md
Mac 下的包管理工具已经添加了对 you-get  的支持。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1190)
> Install via brew (Mac only)

- src/you_get/extractors/bilibili.py
I think the current behavior does not make sense. Sometimes I only want to download or play the specified P ,such as movie collection.
Can we do that according the link?
like that:
for http://www.bilibili.com/video/av3278560/index_1.html  , only download the first
for http://www.bilibili.com/video/av3278560/ ,download all parts
i'm a newcomer to python :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1192)
> [Bilibili] download specified P according to the link

- src/you_get/extractors/iqiyi.py
- src/you_get/extractors/iqiyi_sc.py
thanks @yan12125
根据 @yan12125 的gen_sc以及 #1211 里面的讨论，写的patch：
```
python3 ./you-get -uid http://www.iqiyi.com/v_19rrle48gg.html
[DEBUG] get_content: http://cache.m.iqiyi.com/jp/tmts/493671100/b90c963ff6f3c3c0b542a895de333154/?platForm=h5&rate=2&tvid=493671100&vid=b90c963ff6f3c3c0b542a895de333154&cupid=qc_100001_100186&type=mp4&olimit=0&agenttype=13&src=d846d0c32d664d32b6b54ea48997a589&sc=a11973de9ecc72aaede029c817062e4a&t=1466839003529&__jsT=null
[DEBUG] get_content: http://cache.m.iqiyi.com/jp/tmts/493671100/b90c963ff6f3c3c0b542a895de333154/?platForm=h5&rate=1&tvid=493671100&vid=b90c963ff6f3c3c0b542a895de333154&cupid=qc_100001_100186&type=mp4&olimit=0&agenttype=13&src=d846d0c32d664d32b6b54ea48997a589&sc=33044aeea13ffeb98ce4a2c00ed3e54c&t=146 …
```
> iqiyi: use html5 to fix #1211 , but lose some stream quality

- src/you_get/common.py
- src/you_get/extractors/cntv.py
#1193 : 
```
$ python3 you-get -di   http://sports.cctv.com/2016/06/04/VIDE7dwBLcUeJbebiSoQj62g160604.shtml
Site:       CNTV.com
Title:      [法网]女单决赛：小威廉姆斯VS穆古鲁扎 1
Size:       190.51 MiB (199769403 Bytes)
```
#909 : 
```
$ python3 you-get -di  http://jiankang.cntv.cn/jiankangzhilu/classpage/video/20110930/100261.shtml
Site:       CNTV.com
Title:      《健康之路》 20110930 眩晕之谜
Size:       68.53 MiB (71859047 Bytes)
```
@caorong FYI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1239)
> [CNTV] Fix CCAV domain, Add pattern, fix #1193 ,#909 , replace #1031

- src/you_get/common.py
- src/you_get/extractors/iqiyi.py
- src/you_get/processor/ffmpeg.py
- src/you_get/processor/rtmpdump.py
I am hoping we can use FFmpeg to deal with HLS(for I do not want to write our own dynamic M3U parser). And preferably provide some hints of working with HDS.
So:
I am opening a new function called ```download_url_ffmpeg``` that can be called in extractors that would work just like ```download_rtmpdump_stream```. 
However, since FFmpeg is sooooooooooooo powerful, DO NOT use it to download everything!
@soimort Merge with caution. Not fully tested. PR raised mostly with faith.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1237)
> [Common, ffmpeg]Exp: Add a ffmpeg downloader and player for any URL

- src/you_get/extractors/iqiyi.py
for https://github.com/soimort/you-get/issues/1245
```
python3 you-get -di http://www.iqiyi.com/v_19rrkxmiss.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/453406400/778e9e5286f2ca6a94d8b5da0062f978/?t=1467413662521&sc=bef92c9fcb5de60324b636e700fee7fe&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               太阳的后裔第1集
- format:        BD
container:     m3u8
video-profile: 1080p
size:          0.0 MiB (0 bytes)
- format:        TD
container:     m3u8
video-profile: 720p
size:          0.0 MiB (0 bytes)
- format:        HD
container:     m3u8
video-profile: 540p
size:          0.0 MiB (0 bytes)
- format:        SD
container:     m3u8
video-profile: 360p …
```
> iqiyi: fix when no vip info

- src/you_get/extractors/vk.py
Pull request to allow downloading, publicly available photos from vk.com:
example: you-get  https://new.vk.com/photo2203022_417323584
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1258)
> you get vk photos

- README.md
- src/you_get/extractors/vk.py
fixed videos for vk
example: you-get --debug 'https://new.vk.com/videos-46371384?section=all&z=video-46371384_170674413%2Fclub46371384%2Fpl_-46371384_-2'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1264)
> Lets fix vk videos

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1273)
> add intallation option for chocolatey on windows

- src/you_get/extractors/iqiyi.py
As in #1282 , as requested.
All credits goes to @wwqgtxx .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1285)
> [iQiyi]not import json_output module

- src/you_get/extractors/acfun.py
- src/you_get/extractors/youku.py
Damn it Youku is soooooooooo slow today.
```
$ python3 you-get -di "http://www.acfun.tv/v/ac2938239"
[DEBUG] get_content: http://api.aixifan.com/plays/3873717
[DEBUG] get_content: https://api.youku.com/players/custom.json?client_id=908a519d032263f8&video_id=CNTIxNDgzMg==&embsig=1_1469694033_80f27b8a0fd6f48b35d79c7a1cfeb7f3
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CNTIxNDgzMg==&ct=85&sign=MXwxNDY5Njk0MjY4fDAxZWI5MmQxOTA1MjE2YjJmYmYyNTg5M2QyMTQ2OTVj
[DEBUG] get_content: http://play.youku.com/partner/get.json?cid=908a519d032263f8&vid=CNTIxNDgzMg==&ct=86&sign=MXwxNDY5Njk0MjY4fDAxZWI5MmQxOTA1MjE2YjJmYmYyNTg5M2QyMTQ2OTVj
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/6469694269478867b886e_00/st/flv/fileid/0300020D0057989E6BCD892D9B7D2FF0 …
```
> Fix Acfun failed

- src/you_get/processor/ffmpeg.py
Or:
```
File "you-get", line 11, in <module>
File "/Users/***/you-get/src/you_get/__main__.py", line 92, in main
main(**kwargs)
File "/Users/Beining/Documents/coding/you-get/src/you_get/common.py", line 1331, in main
File "/Users/Beining/Documents/coding/you-get/src/you_get/common.py", line 1244, in script_main
download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
File "/Users/Beining/Documents/coding/you-get/src/you_get/common.py", line 1060, in download_main
download(url, **kwargs)
File "/Users/Beining/Documents/coding/you-get/src/you_get/common.py" …
```
> [Processor]FFmpeg: check arguments not None

- src/you_get/extractors/douyutv.py
Use lapi from web swf player
Thanks #1299 @cnbeining #1235 @hellofwy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1315)
> [Douyutv]Update api

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/bigthink.py
Here in ```you-get```, you would expect an feature request being implemented in 3.5 years.
```
$ python3 you-get -di "http://bigthink.com/videos/maria-konnikova-on-how-to-recognize-and-subvert-the-con-artist"
[DEBUG] get_content: http://bigthink.com/videos/maria-konnikova-on-how-to-recognize-and-subvert-the-con-artist
[DEBUG] get_content: https://edge.api.brightcove.com/playback/v1/accounts/115485138001/videos/5050938393001
site:                Bigthink
title:               Mind Games: How to Recognize and Subvert A Con Artist&#x27;s Scam
- format:        1080
size:          699.3 MiB (733243662 bytes)
- format:        288
size:          29.3 MiB …
```
> [Bigthink]Add Bigthink, fix #64

- src/you_get/extractors/qq.py
```
python3 you-get -di "http://daxue.qq.com/content/content/id/2650"
Site:       QQ.com
Title:      卢青伟：让每个企业都有自己的微信
Size:       79.49 MiB (83351234 Bytes)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1329)
> [QQ]Add QQ Daxue

- src/you_get/extractors/ifeng.py
./you-get -i http://v.ifeng.com/mil/mainland/201608/01611fb6-5a0e-11e6-a426-002590c2aaeb.shtml
Site:       ifeng.com
Title:      江西 岗位坚守 武警战士高温下训练
Size:       9.71 MiB (10178666 Bytes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1330)
> [ifeng] fix video info xml url

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/wanmen.py
```
$ python3 you-get -di "http://www.wanmen.org/#/course/1?tIndex=0&pIndex=5" 
[DEBUG] get_content: http://api.wanmen.org/course/getCourseNested/1
[DEBUG] get_content: http://p.bokecc.com/servlet/playinfo?vid=C6F35F853B57D46D9C33DC5901307461&m=0
site:                BokeCC
title:               法语快速入门_Enchanté  幸会_姓名
- format:        2002
video-profile: 高清 2.0x
size:          17.5 MiB (18398761 bytes)
- format:        2003
video-profile: 超清 2.0x
size:          32.9 MiB (34487591 bytes)
- format:        1
video-profile: 清晰
size:          19.7 MiB (20698367 bytes)
- format:        2
video-profile: 高清
size:          35.1 …
```
> [Wanmen]Add support

- src/you_get/extractors/youku.py
This is a fix for the short commercial in the end of the videos from youku it is not a pretty ix but fixed it in the examples give.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1407)
> Fix for #1405

- src/you_get/extractors/qq.py
Prefer 1080p and 720p if available
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1428)
> Tencent Video use best quality

- src/you_get/extractors/acfun.py
Fixed AcFun extractor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1446)
> [AcFun] fix #1429

- index.html
- index.md
you-get.org is server over https so images should be secured to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1447)
> Fix http/https mixed content on index page

- src/you_get/common.py
- src/you_get/extractors/huomaotv.py
huomao.tv demo
```
you-get -i http://www.huomao.com/717
Site:       huomao.com
Title:      【FA】LGD VS Ehome_火猫直播_年轻人的直播社区
Type:       Unknown type (m3u8)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1468)
> [huomaotv] add huomao.com suppport

- src/you_get/extractors/youku.py
Fix extraction of video segments hosted by domain `vali.cp31.ott.cibntv.net`, per #1485.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1486)
> [Youku] Revert #1407

- src/you_get/common.py
Add support for downloading the dynamic video URLs from some annoying site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1478)
> common: add dynamic url support for `url_save_chunked`

- README.md
- src/you_get/extractors/douban.py
Example links:
- https://movie.douban.com/trailer/206529/
- https://movie.douban.com/trailer/206457/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1493)
> Add support: movie.douban.com

- src/you_get/extractors/bilibili.py
- Fix #1391, #1436.
- Replace #1471, #1438.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1494)
> [Bilibili] Fix Bangumi support using post_content

- src/you_get/extractors/youtube.py
@soimort-bot And here's the cat.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1505)
> [YouTube] Fix #1502

- src/you_get/extractors/mgtv.py
1. Fix video url matcher
2. Change container from FLV to TS
3. Use m3u8 ext-info for fast size calculate
4. Use m3u8 url for video playing
Some test urls:
http://www.mgtv.com/b/298050/3690375.html
http://www.mgtv.com/b/294045/3348671.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1511)
> [MGTV] Some fixes. Because it's not working

- src/you_get/extractors/yixia.py
Miaopai has two styles of URL
1. http://www.miaopai.com/show/-FIqw~8q9R1qq~gSm0tUGA__.htm
2. http://www.miaopai.com/show/KDzmatlzeXnYSve4Z1Bdjg__.htm
and `\w` can't match style 1, so i changed `\w+` to `.+`, this could fix problem in #1346 
ping @cnbeining @soimort
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1513)
> update yixia_download url match rule, fix #1346 

- src/you_get/common.py
fix syntax error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1525)
> fix bug about renaming videos when downloading with ffmpeg

- src/you_get/extractors/tudou.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1528)
> [Tudou] Fix titles in playlists

- src/you_get/extractors/qq.py
I have tried $ you-get --debug -i http://daxue.qq.com/content/content/id/2937
and got "NameError: name 'output_json' is not defined" for
fvkey = output_json['vl']['vi'][0]['fvkey']
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1532)
> fix for NameError: name 'output_json' is not defined

- src/you_get/extractors/magisto.py
Use the api instead of finding the source on the page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1559)
> Fix for magisto

- src/you_get/extractors/bilibili.py
modify the regex to get eposide id
bilibili has changed their html source code, change the regex would help fix issue #1569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1586)
> fix bilibili bangumi support

- README.md
- src/you_get/common.py
- src/you_get/extractors/quanmin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1591)
> Support for quanmin.tv.

- src/you_get/extractor.py
修复youku用vid下载报错导致不能下载列表所有视频的问题
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1581)
> Fix soku.com vid download error problem

- src/you_get/extractors/panda.py
Could not get the rebase to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1620)
> Fix for panda.tv #1612

- src/you_get/common.py
Originally all timeout are from get_content for me, so I send #1159, but recently the timeout starts to appear in url_save too, so in order to be future proof, I just replaced every request.urlopen (that's not in a deprecated function) with urlopen_with_retry.
As you can see from the log, my download speed is pretty fast, but it still occasionally got stuck during downloading and eventually timeout.
```
31.6% (305.5/965.8MB) ├█████████████──────────────────────────┤[ 6/19]   10 MB/syou-get: version 0.4.626, a tiny downlo
ader that scrapes the web.                                                                                             
you-get: ['http://v.youku.com/v_show/id_<random_id>.html']                                                             
Traceback (most recent call …
```
> [common] also retry if timeout in url_save, post_content, etc.

- src/you_get/extractors/zhanqi.py
#992 #1497 #1049
zhanqi 的开发很小白，留下的坑很多，比如地址后面竟然有 \r\n。
还加上了对 /topic/ 这样url滥用的支持。。。。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1648)
> fix:[zhanqi.tv]recode all

- src/you_get/extractors/youtube.py
I improved YouTube livestream detection by using `livestream` value and `live_playback` value in `ytplayer_config['args']`.
This improvement also fix issue #1673.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1674)
> [youtube] improve livestream detection, fix #1673

- src/you_get/processor/ffmpeg.py
Prevent FFmpeg from consuming stdin and interpreting the character stream as a stream of interactive commands, specifically:
?      show this help
+      increase verbosity
-      decrease verbosity
c      Send command to first matching filter supporting it
C      Send/Queue command to all matching filters
D      cycle through available debug modes
h      dump packets/hex press to cycle through the 3 states
q      quit
s      Show QP histogram
This is mostly useful in a batch environment where an unsuspecting user
may not realize you-get could consume stdin through FFmpeg, e.g.
```sh
while read url; do you-get "$url"; done <urllist
```
(Related: BashFAQ/089.)
Yeah, apparently the above could easily be replaced with `xargs you-get <urllist` which is more elegant and doesn't suffer from the …
> [ffmpeg] call ffmpeg with stdin redirected to the null device

- src/you_get/extractors/mgtv.py
- src/you_get/json_output.py
2017/1/17 mgtv.com change video info api,fit it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1628)
> mgtv.com 2017/1/17 change api address and stream domain

- src/you_get/extractors/ckplayer.py
- src/you_get/extractors/dilidili.py
test case:
```
./you-get -i 'http://www.dilidili.com/watch3/54829/' 'http://www.dilidili.wang/watch3/54829/' 'http://www.dilidili.mobi/watch3/54829'
```
```
Site:       CKPlayer General
Title:      人渣的本愿 第3话
Size:       207.6 MiB (217684108 Bytes)
Site:       CKPlayer General
Title:      人渣的本愿 第3话
Size:       207.6 MiB (217684108 Bytes)
Site:       CKPlayer General
Title:      人渣的本愿 第3话
Size:       207.6 MiB (217684108 Bytes)
```
```
./you-get -i ''http://www.dilidili.com/watch3/48104/''
```
```
Site:       CKPlayer General
Title:      双星之阴阳师 第19话 无论是罪孽还是污秽
Size:       149.87 MiB (157154818 Bytes)
```
---
This change is [<img …
> fix #1663 for dilidili

- .gitignore
- src/you_get/common.py
- src/you_get/extractors/ximalaya.py
test case:
1. single
```
./you-get 'http://www.ximalaya.com/5916736/sound/27694473'
Site:        ximalaya.com
title:       【奇迹暖暖原创同人曲】叶格尔的情诗
Type:        MPEG-4 audio m4a
Size:        N/A
Downloading 【奇迹暖暖原创同人曲】叶格尔的情诗.m4a ...
100% (  1.8/  1.8MB) ├█████████████████████████████████████████┤[1/1]    2 MB/s
```
2. album
```
./you-get -dl 'http://www.ximalaya.com/5916736/album/6293696'
[DEBUG] get_content: http://www.ximalaya.com/5916736/album/6293696
[DEBUG] get_content: http://www.ximalaya.com/5916736/album/6293696
[DEBUG] get_content: http://www.ximalaya.com/tracks/27694500.json
[DEBUG] ximalaya_download_by_id: http://audio.xmcdn.com/group22/M04/08/59/wKgJLlhjMMzD_aIHAC-t6uS6CVc270.m4a
Site:        ximalaya.com
title:       再起荣耀——《全职高手》宣传曲
Type:        MPEG-4 audio m4a
Size:        N/A …
```
> Support ximalaya

- src/you_get/json_output.py
Change "NameError" to "AttributeError" in json_output.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1776)
> Fix json output

- src/you_get/extractors/qq.py
Enable you-get to deal with videos with keyid that > 11000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1785)
> Fix qq video error; Fix #1778

- src/you_get/extractors/vine.py
#1786
extra test case
```
./you-get -di 'https://vine.co/v/57ilJ1KanWJ'
[DEBUG] get_html: http://vine.co/v/57ilJ1KanWJ
[DEBUG] get_response: http://vine.co/v/57ilJ1KanWJ
[DEBUG] get_content: https://archive.vine.co/posts/57ilJ1KanWJ.json
[DEBUG] url_info: http://v.cdn.vine.co/r/videos_dashhd/C40B136F021365174982178762752_53f4484ad8e.25.1.ADDA1E67-CF16-4C3B-901A-DE068DE26134.mp4?versionId=m3186a1ti_Xe8IzkYm83TSPmLo6LzYKZ
Site:       Vine.co
Title:      Littering.
Size:       1.25 MiB (1312099 Bytes)
```
test case
```
/you-get -di 'https://vine.co/v/iFDvMVePn7n'
[DEBUG] get_html: http://vine.co/v/iFDvMVePn7n
[DEBUG] get_response: http://vine.co/v/iFDvMVePn7n
[DEBUG] get_content: https://archive.vine.co/posts/iFDvMVePn7n.json
[DEBUG] url_info: …
```
> [vine]fix vine

- src/you_get/common.py
- src/you_get/extractors/yizhibo.py
Support for yizhibo.com
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1550)
> Yizhibo support

- src/you_get/extractors/qq.py
#1754
test case 1: (kg2.qq.com)
```
./you-get 'http://kg2.qq.com/share.html?s=qqJuE9qtVgx1IqzS'
Site:       腾讯全民K歌
Title:      情歌王
Type:       MPEG-4 audio (audio/mp4)
Size:       1.09 MiB (1139329 Bytes)
Downloading 情歌王.mp4 ...
100% (  1.1/  1.1MB) ├█████████████████████████████████████████████┤[1/1]    2 MB/s
ls | grep '情歌王'
情歌王.lrc
情歌王.mp4
```
test case 2 (kg.qq.com, a video)
```
./you-get -d 'http://kg.qq.com/share.html?s=VKzj9kVgqBbhLVVp'
[DEBUG] get_content: http://cgi.kg.qq.com/fcgi-bin/kg_ugc_getdetail?dataType=jsonp&jsonp=callback&jsonpCallback=jsopgetsonginfo&v=4&outCharset=utf-8&shareid=VKzj9kVgqBbhLVVp
[DEBUG] get_content: http://cgi.kg.qq.com/fcgi-bin/fcg_lyric?jsonpCallback=jsopgetlrcdata&outCharset=utf-8&ksongmid=002qggKE4IjhEn
[DEBUG] url_info: …
```
> add support for kg.qq.com

- src/you_get/extractors/ifeng.py
#1834
test case
```
/you-get -di 'http://v.ifeng.com/video_6169467.shtml'
[DEBUG] get_content: http://v.ifeng.com/video_6169467.shtml
[DEBUG] get_html: http://vxml.ifengimg.com/video_info_new/3/34/01c7977b-aed6-4a98-bf20-6558bdb28734.xml
[DEBUG] get_response: http://vxml.ifengimg.com/video_info_new/3/34/01c7977b-aed6-4a98-bf20-6558bdb28734.xml
[DEBUG] url_info: http://ips.ifeng.com/video19.ifeng.com/video09/2017/03/29/4566902-102-078-2335.mp4
Site:       ifeng.com
Title:      台湾东岸战略凸显 解放军潜艇突破岛链要津
Size:       186.84 MiB (195916578 Bytes)
```
> add ifeng new matching patterns

- src/you_get/common.py
#1726
#1731
> also import the links through the text file can ignore the annoying "" signs
Test Case: long flag
```
./you-get -id --input-file urls.txt
[DEBUG] you are trying to load urls from urls.txt
[DEBUG] get_content: http://www.bilibili.com/video/av8934646/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=14747980&from=miniplay&player=1&sign=3ac188621448f4ef8b010919b6243a0a
[DEBUG] url_info: http://cn-sdjn-cu-v-07.acgvideo.com/vg1/7/16/14747980-1.flv?expires=1488786000&platform=pc&ssig=P5GjKV8fhguXUNlGepVIWw&oi=3060929956&nfa=B2jsoD9cEoAmG7KPYo7s2g==&dynamic=1
Site:       bilibili.com
Title:      【超欢乐！】龙女仆真是太可爱啦！
Size:       42.42 MiB (44480482 Bytes)
[DEBUG] get_content: http://www.bilibili.com/video/av8946951/
[DEBUG] …
```
> Add -I --input-file flag

- src/you_get/extractors/tudou.py
fix #1670 
test case
``` .
./you-get http://www.tudou.com/programs/view/EpCNEFK2Su4/
```
```
Site:       Tudou.com
Title:
Size:       213.79 MiB (224172131 Bytes)
Downloading .f4v ...
0.0% (  0.0/213.8MB) ├─────────────────────────────────────────┤[1/9]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1708)
> fix tudou.py when there is no title

- src/you_get/extractors/douyutv.py
from https://gist.github.com/spacemeowx2/629b1d131bd7e240a7d28742048e80fc
#1720
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1734)
> [douyu]use new api

- src/you_get/extractors/le.py
#1925
test case
```
$ ./you-get -i 'http://www.le.com/ptv/vplay/29198619.html'
Current Video Supports:
--format 1300 <URL>
--format 1080p <URL>
--format 350 <URL>
--format 720p <URL>
--format 1000 <URL>
Site:       Le.com
Title:      外科风云30
Size:       1011.81 MiB (1060964652 Bytes)
```
> [le.py] update api

- src/you_get/extractors/qq.py
Now some ```v.qq.com/page``` redirected by HTTP 302: #1908
test case
```
./you-get -di 'http://v.qq.com/page/a/0/g/a01714fzv0g.html'
[DEBUG] url_locations: http://v.qq.com/page/a/0/g/a01714fzv0g.html
[DEBUG] get_response: https://v.qq.com/x/page/a01714fzv0g.html
[DEBUG] get_response: http://vv.video.qq.com/getinfo?otype=json&appver=3%2E2%2E19%2E333&platform=11&defnpayver=1&vid=a01714fzv0g
[DEBUG] get_response: http://vv.video.qq.com/getkey?otype=json&platform=11&format=10701&vid=a01714fzv0g&filename=a01714fzv0g.p701.1.mp4
[DEBUG] url_info: http://42.236.95.151/vhot2.qqvideo.tc.qq.com/a01714fzv0g.p701.1.mp4?vkey=51E23FF9507E1D542F1FDC3D41C1274C7AD8FA110C319E3B805B9977B58E3F498E2C8EB7D8D9AB27338FFE18C51DF81BA483EB18F146B8A35B9A269F183BE3E744224776151DFB328F9A76B0E925C3D286BB749406C5B96E83EC6 …
```
> [qq]fix v.qq.com/page redirect

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/ucas.py
Fix #75 .
```
$ python3  you-get --debug --json "http://v.ucas.ac.cn/course/getplaytitle.do?menuCode=2&code=14035&classcode=1&classid=2bmk9DBRqpaum9KTpW&sectionNumber=1&sectionDisplay=1"
[DEBUG] get_content: http://v.ucas.ac.cn/course/getplaytitle.do?menuCode=2&code=14035&classcode=1&classid=2bmk9DBRqpaum9KTpW&sectionNumber=1&sectionDisplay=1
[DEBUG] Starting new HTTP connection (1): 210.76.211.10
[DEBUG] http://210.76.211.10:80 "GET /vplus/remote.do?method=query&loginname=videocas&pwd=af1c7a4c5f77f790722f7cae474c37e281203765d423a23b&resource=%5B%7B%22resourceID%22%3A%2276ff2721-c3e1-4b6b-a855-2a6d27212847%22%2C%22on%22%3A1%2C%22time%22%3A60000%2C%22eid%22%3A100%2C%22w%22%3A800%2C%22h%22%3A600%7D%5D&timeStamp=1494710032 HTTP/1.1" 200 948
[DEBUG] Starting new HTTP connection (1): …
```
> [UCAS] Add support, fix #75

- src/you_get/extractors/sina.py
#500
```
./you-get -i 'http://video.sina.com.cn/news/spj/topvideoes20150304/?opsubject_id=top1#137380095'
Site:       Sina.com
Title:      惠州博罗：红火蚁围村 村民谈蚁色变
Size:       24.66 MiB (25858597 Bytes)
```
better than nothing?
> [sina]try to find vid from url

- src/you_get/extractors/le.py
#1000
#1200
#1469
```
./you-get -i 'http://www.le.com/ptv/vplay/24902320.html' 'http://sports.le.com/video/25737697.html'
Current Video Supports:
--format 1000 <URL>
--format 1300 <URL>
--format 350 <URL>
--format 720p <URL>
Site:       Le.com
Title:      F1澳大利亚站排位赛（车载）全场回顾
Size:       704.18 MiB (738387296 Bytes)
Current Video Supports:
--format 1000 <URL>
--format 1300 <URL>
--format 350 <URL>
--format 720p <URL>
Site:       Le.com
Title:      美洲杯-梅西替补戴帽阿圭罗破门 阿根廷5-0晋级
Size:       57.23 MiB (60012608 Bytes)
```
> [le]support sports.le

- src/you_get/extractors/yixia.py
- tests/test.py
miao pai mobile page url does not contains .htm, so fix it when get scid
> fix miaopai mobile page download

- src/you_get/extractors/pptv.py
```
$  ./you-get -d -i http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2
[DEBUG] get_content: http://v.pptv.com/show/xEKoJ4ic1ZaMGhOw.html?rcc_src=X2
[DEBUG] get_content: http://web-play.pptv.com/webplay3-0-17285316.xml?type=web.fpp&version=4
site:                PPTV
title:               金玉良缘(第01集)
- format:        4
video-profile: 1920x1072@6038kbps
size:          1964.8 MiB (2060200621 bytes)
- format:        3
video-profile: 1920x1072@2329kbps
size:          757.9 MiB (794703362 bytes)
- format:        2
video-profile: 1280x712@1054kbps
size:          343.3 MiB (359971308 bytes)
- format:        1 …
```
> [pptv]refactor

- src/you_get/common.py
- src/you_get/extractors/acfun.py
```
$ ./you-get -i http://www.acfun.cn/v/ac3498708 http://www.acfun.cn/v/ac2678901
Site:       AcFun.tv
Title:      各种宠物的错误打开方式 - ⑧月份的幻想酱
Size:       124.42 MiB (130468221 Bytes)
Site:       AcFun.tv
Title:      滑稽的宠物 - 柏斯布德绮姐
Size:       30.07 MiB (31534354 Bytes)
```
```
$ ./you-get -i http://www.acfun.cn/v/ac3627993
Site:       AcFun.tv
Title:      【日剧】月付百万的女人们 02 配信版【Melonpan字幕组】 - 慕藍zzz
Size:       289.78 MiB (303859436 Bytes)
```
2nd commit fix #2043
fixed: #2008 #1914 #1696
outdated: #1339 #1629
> [acfun]fix youku cloud source

- src/you_get/extractors/instagram.py
A backport of my you-get-powered script [`Get-Insta`](https://github.com/soimort/dotfiles/blob/master/Scripts/Get-Insta).
```
$ ./you-get -d https://www.instagram.com/p/BVo74hEl8d5/ 
[DEBUG] get_response: http://www.instagram.com/p/BVo74hEl8d5/
[DEBUG] get_head: https://instagram.fcph1-1.fna.fbcdn.net/t51.2885-15/e35/19367159_460067827702307_7254194888156119040_n.jpg
Site:       Instagram.com
Title:      BVo73CuFISi
Type:       JPEG Image (image/jpeg)
Size:       1.48 MiB (1554643 Bytes)
Downloading BVo73CuFISi.jpg ...
100% (  1.5/  1.5MB) ├███████████████████████████████████┤[1/1]   10 MB/s
[DEBUG] get_head: https://instagram.fcph1-1.fna.fbcdn.net/t51.2885-15/e35/19429042_672445906292526_8042537294978088960_n.jpg
Site:       Instagram.com
Title:      BVo73EjFqmR
Type:       JPEG Image …
```
> [Instagram] Support multiple image posts

- src/you_get/extractors/youku.py
Test links:
* http://v.youku.com/v_show/id_XMTUzOTc1MTAyOA==.html
Password: `test`
* http://v.youku.com/v_show/id_XMzg1ODY1MTIw.html
Password: `123`
> [Youku] Fix support for password-protected videos

- src/you_get/extractors/quanmin.py
fix #1653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1654)
> fix quanmin.py

- src/you_get/extractors/acfun.py
> add new acfun's url pattern

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/fantasy.py
人人拆不开 fantasy肯定有一腿 姑且先放上。
```
$ python3  you-get --debug --json "http://www.fantasy.tv/video/play.html?tvId=12764&channelId=146"
[DEBUG] get_content: http://www.fantasy.tv/tv/playDetails.action?myChannelId=1&id=12764&channelId=146&t=0.6768107829821273
[DEBUG] url_info: http://oss.fantasy.tv/video/39/146/1500191644488191.mp4?Expires=1503035306&OSSAccessKeyId=5yUBMpd3qmt5pIH7&Signature=ngeZo3drK%2BOUWqSlkZsueUfD6%2FA%3D
{
"site": "fantasy.tv",
"streams": {
"__default__": {
"container": "mp4",
"size": 719621279,
"src": [
"http://oss.fantasy.tv/video/39/146/1500191644488191.mp4?Expires=1503035306&OSSAccessKeyId=5yUBMpd3qmt5pIH7&Signature=ngeZo3drK%2BOUWqSlkZsueUfD6%2FA%3D"
],
"video_profile": "__default__"
}
},
"title": "纸牌屋.House.Of.Cards.2013.S05E01.中英字幕.WEB-HR.AAC.720P.x264-人人影视",
"url": …
```
> [Fantasy] Add support

- src/you_get/common.py
thanks to @ayanamist
https://github.com/soimort/you-get/commit/bcd8d74d73f13f310a92929c5654e208ef5140eb#commitcomment-24242276
This error was introduced in pr #2260.
> fix wrong local name

- src/you_get/extractors/bilibili.py
Based on my observation, #2377 can be resolved by simply enforcing a socket timeout. (like #1788)
> [Bilibili] Workaround for speed limiting issue

- src/you_get/extractors/pptv.py
> [pptv] fix #2422

- src/you_get/extractors/twitter.py
> twitter download fix case https://twitter.com/Newstv_jp/status/914293814054891521

- src/you_get/extractors/youku.py
fix issues #2405 with out merge problem
> Update youku.py fix issues #2405

- src/you_get/extractors/qq.py
I don't know why. But downloading qq video seemed not worked well. I delete some lines. Then it works.
> qq video does not work well any more

- src/you_get/extractors/douyutv.py
感谢您的pull request! `you-get`是稳健成长的开源项目，感谢您的贡献.
以下简单检查项目望您复查:
作为贡献者，您需要知悉
不是所有的pull requests都会被合并,然而我认为合并/不合并的补丁一样重要：如果您认为补丁重要，其他人也有可能这么认为，那么他们可以从你的fork中提取工作并获益。无论如何，感谢您费心对本项目贡献.
祝好,
Mort
> add header and update douyutv api fix StatusCode 403

- src/you_get/common.py
In order to better read and understand the code, I updated the common.py based on the pep8 guideline(no logic change)
> pep8 update for common.py

- src/you_get/extractors/bilibili.py
The HTML page of a live page does not carry any room info now. Room ID
and title needs to be retrieved with proper API calls.
Fixes #2479.
> [bilibili] fix livestream extractor

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/coub.py
- src/you_get/processor/ffmpeg.py
Video and audio files with high quality are downloaded.
We use ffmpeg for audio and video combining into one file
> [coub] add coub.com support

- src/you_get/common.py
- src/you_get/extractors/toutiao.py
Add suport for downloading toutiao video,  test urls: 
> http://www.365yg.com/group/6402884341996159234/
> add suport for toutiao.com

- src/you_get/extractors/coub.py
Add different video and quality support
> [coub] added quality support

- README.md
- src/you_get/common.py
- src/you_get/extractors/ixigua.py
```
you-get --debug https://www.ixigua.com/a6485678187131961870/#mid=6570317571
[DEBUG] get_content: https://www.ixigua.com/a6485678187131961870/#mid=6570317571
[DEBUG] get_content: http://i.snssdk.com/video/urls/v/1/toutiao/mp4/5ef15c87a1cd43b9bcf03950eba57f4c?r=00797916017804523&s=2360975152
[DEBUG] url_info: http://v1-tt.ixigua.com/799a2b12b0c80b88023006f583396cbe/5a2cc116/video/m/2208a325d116d2f4c368f647c3cd6115b411152348a00002b89627602da/
Site:       ixigua.com
Title:      丧尸爆发！人才是最大的威胁？
Size:       9.27 MiB (9719816 Bytes)
Downloading 丧尸爆发！人才是最大的威胁？.mp4 ...
100% (  9.3/  9.3MB) ├████████████████████████████████████████┤[1/1]   20 MB/s
```
```
you-get --debug -l https://www.ixigua.com/c/user/61109961001/ …
```
> [ixigua] Add support 

- src/you_get/common.py
Not all pull requests can eventually be merged. I consider merged / unmerged patches as equally important for the community: as long as you think a patch would be helpful, someone else might find it helpful, too, therefore they could take your fork and benefit in some way. In any case, I would like to thank you in advance for taking your time to contribute to this project.
Cheers,
Mort
**(PLEASE REPLACE ALL ABOVE WITH A DETAILED DESCRIPTION OF YOUR PULL REQUEST)** …
> Fix download_url_ffmpeg extension

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/kuaishou.py
Add support for https://www.kuaishou.com/
support video and image
> New site support: https://www.kuaishou.com/

- src/you_get/extractors/qq.py
Not all pull requests can eventually be merged. I consider merged / unmerged patches as equally important for the community: as long as you think a patch would be helpful, someone else might find it helpful, too, therefore they could take your fork and benefit in some way. In any case, I would like to thank you in advance for taking your time to contribute to this project.
Cheers,
Mort
**(PLEASE REPLACE ALL ABOVE WITH A DETAILED DESCRIPTION OF YOUR PULL REQUEST)** …
> fix https://v.qq.com/x/cover/9hpjiv5fhiyn86u/t0522x58xma.html

- src/you_get/extractors/douyutv.py
m.douyu.com DOES have the unique room_id, for counter-example: https://www.douyu.com/aleng1106, there is no room_id in this page
Not all pull requests can eventually be merged. I consider merged / unmerged patches as equally important for the community: as long as you think a patch would be helpful, someone else might find it helpful, too, therefore they could take your fork and benefit in some way. In any case, I would like to thank you in advance for taking your time to …
> update douyutv.py for room_id bugs

- src/you_get/extractors/bilibili.py
A small fix for the bangumi scraping
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/2565)
> bilibili: adapt to new bangumi API

- src/you_get/extractors/qq.py
The url of v.qq.com has been changed. The code needs to be renewed.
> fix the bug of v.qq.com

- src/you_get/extractors/longzhu.py
Import the definition of __general_m3u8_extractor()__ for the function call on line 64...
flake8 testing of https://github.com/soimort/you-get on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./src/you_get/extractors/longzhu.py:63:20: F821 undefined name 'general_m3u8_extractor'
urls = general_m3u8_extractor(real_url)
^
1     F821 undefined name 'general_m3u8_extractor'
```
Not all pull requests can eventually be merged. I …
> from ..common import general_m3u8_extractor

- src/you_get/extractors/youku.py
> [youku] use default ckey

- src/you_get/extractors/qq.py
Not all pull requests can eventually be merged. I consider merged / unmerged patches as equally important for the community: as long as you think a patch would be helpful, someone else might find it helpful, too, therefore they could take your fork and benefit in some way. In any case, I would like to thank you in advance for taking your time to contribute to this project.
Cheers,
Mort
**(PLEASE REPLACE ALL ABOVE WITH A DETAILED DESCRIPTION OF YOUR PULL REQUEST)** …
> fix https://v.qq.com/x/page/q0527wsyqpv.html

- src/you_get/extractors/bilibili.py
update xml-url and sec1 to get all format of bilibili-video
> fix bilibili format

- src/you_get/extractors/youku.py
Update cccode to 0510 for youku.py
Get from:
http://g.alicdn.com/player/ykplayer/0.5.28/youku-player.min.js
{"0505":"interior","050F":"interior","0501":"interior","0502":"interior","0503":"interior","0510":"adshow","0512":"BDskin","0590":"BDskin"}
Before the fix:
```
you-get --debug http://v.youku.com/v_show/id_XMzU5NjkxNTM1Ng==.html?spm=a2h0z.8244218.2371631.5
[DEBUG] get_content: https://ups.youku.com/ups/get.json?vid=XMzU5NjkxNTM1Ng==&ccode=0502&client_ip=192.168.1.1&utid=%2BoR%2BE7ve%2BDsCARi5QmohYOQw&client_ts=1526175486&ckey=DIl58SLFxFNndSV1GFNnMQVYkx1PP5tKe1siZu/86PR1u/Wh1Ptd%2BWOZsHHWxysSfAOhNJpdVWsdVJNsfJ8Sxd8WKVvNfAS8aS8fAOzYARzPyPc3JvtnPHjTdKfESTdnuTW6ZPvk2pNDh4uFzotgdMEFkzQ5wZVXl2Pf1/Y6hLK0OnCNxBj3%2Bnb0v72gZ6b0td%2BWOZsHHWxysSo/0y9D2K42SaB8Y/%2BaD2K42SaB8Y/%2BahU%2BWOZsHcrxyso …
```
> [youku] Update cccode

- src/you_get/extractors/douyutv.py
修复斗鱼TV403错误:
```
you-get --debug https://v.douyu.com/show/NbwE7ZBGkVR7n5Zz
[DEBUG] get_content: https://v.douyu.com/show/NbwE7ZBGkVR7n5Zz
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
[DEBUG] HTTP Error with code403
```
完成修复后:
```
you-get --debug https://v.douyu.com/show/NbwE7ZBGkVR7n5Zz
[DEBUG] get_content: https://v.douyu.com/show/NbwE7ZBGkVR7n5Zz
[DEBUG] get_content: http://vmobile.douyu.com/video/getInfo?vid=NbwE7ZBGkVR7n5Zz
[DEBUG] get_content: http://videows1.douyucdn.cn/live/normal_251743420180510183220-upload-609c/playlist.m3u8?k=5ff9b5b48a9a50e2737bab9df7d3fa67&t=5af514b4&u=0&ct=h5&vid=4083361&d=f0e87828a27535574a3b063f6f90aabc
Site:       Douyu Video
Title:      冯提莫《下一站天后》我爱唱歌，你爱听吗 ❤
Type:       M3U8 Playlist m3u8
M3U8 Url: …
```
> 修复斗鱼TV403错误

- .travis.yml
Another attempt at #2145
Output: https://travis-ci.org/soimort/you-get/jobs/380561806#L453-L458
> Add flake8 to the testing (again)

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/acfun.py
- src/you_get/extractors/bilibili.py
- src/you_get/extractors/qq.py
- src/you_get/extractors/zhibo.py
fix some url format from v.qq.com:
https://v.qq.com/x/page/w0674l9yrrh.html
http://v.sports.qq.com/#/cover/t0fqsm1y83r8v5j/a0026nvw5jr
> fix some url format from v.qq.com

- src/you_get/extractors/bilibili.py
the old cid pattern match is broken, fix it with the new one.
> fix cid match

- src/you_get/extractors/bilibili.py
```sh
⋊> ~/repos/you-get/you-get -i 'https://www.bilibili.com/video/av16907446?p=3'
you-get: This page contains a playlist. (use --playlist to download all videos.)
site:                Bilibili
title:               "不要相信歌词，他们为了押韵什么都干得出来" #3. 居然还有P3!
streams:             # Available quality and codecs      ^^^^^^^^^^^^^^^
[ DEFAULT ] _________________________________                  \
- format:        flv720                                         `--------- subtitle
size:          18.1 MiB (18994910 bytes)
- format:        flv
size:          13.2 MiB (13799463 bytes)
```
> [bilibili] add subtitle for downloading single episode

- src/you_get/extractors/qq.py
support view.inews.qq.com/a/20180521V0Z9MH00 https://kuaibao.qq.com/s/20180521V0Z9MH00 https://v.qq.com/x/cover/t0fqsm1y83r8v5j/a0026nvw5jr.html
Not all pull requests can eventually be merged. I consider merged / unmerged patches as equally important for the community: as long as you think a patch would be helpful, someone else might find it helpful, too, therefore they could take your fork and benefit in some way. In any case, I would like to thank you in advance for taking …
> Support more links

- src/you_get/extractors/bilibili.py
- tests/test.py
Add a support to download the bilibili user space folder videos.
An example url is:
[https://space.bilibili.com/64169458/#/favlist?fid=1840028](https://space.bilibili.com/64169458/#/favlist?fid=1840028)
> Feature: support download bilibili space favorite folder files

- src/you_get/extractors/yixia.py
> Update miaopai api

- src/you_get/extractors/acfun.py
> fix acfun flv support

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/tiktok.py
Example:
```
$ you-get -d https://t.tiktok.com/i18n/share/video/6625554964976504066/ 
[DEBUG] get_response: https://t.tiktok.com/i18n/share/video/6625554964976504066/
[DEBUG] url_info: http://v16-tiktokcdn-com.akamaized.net/81abd94b5b7a6bb4966bc427b654967f/5c021bab/video/n/v0102/cde8877ad5054d6e93fdf245da30db71/?rc=MzY7aGw2djllaTMzOTgzM0ApQHRud2xAbzxGOzU0Njg0NDs5OjM0OzNAKXUpQGczdylAZmV6ZXpud2xAKTs0ZGJqaWRhaG4zbV8tLS8vNHNzLW8jbGhxbyM0MzItLi0uLS0yLy4wLi4vaTpiLW8jOmAtbyNiK2IrbGhxYC0uOg%3D%3D
Site:       TikTok.com
Title:      小栗有以 on Tik Tok: TikTok
Size:       1.35 MiB (1417465 Bytes)
Downloading 小栗有以 on Tik Tok: TikTok.mp4 ...
100% (  1.4/  1.4MB) ├██████████████████████████████████████████████████████████████████████████████┤[1/1]   12 MB/s
```
> [TikTok] New site support

- src/you_get/extractors/ixigua.py
The ixigua download will result in such an error:
Now it can start working:
playlist:
> fix ixigua downloading failure

- src/you_get/extractors/miaopai.py
Improve support for the following addresses:
- <http://weibo.com/tv/v/EFSNuE1Ky>
- <https://weibo.com/5396121198/GvXa3g1tp?refer_flag=1001030103_&type=comment>
- <http://video.weibo.com/show?fid=1034:1c5b42e8703e5e5c3859c97c27cec374>
> [miaopai] fix weibo.com download error

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/zhihu.py
Add zhihu.com support
play list:
>  [zhihu] Add zhihu.com support

- src/you_get/common.py
Not all pull requests can eventually be merged. I consider merged / unmerged patches as equally important for the community: as long as you think a patch would be helpful, someone else might find it helpful, too, therefore they could take your fork and benefit in some way. In any case, I would like to thank you in advance for taking your time to contribute to this project.
Cheers,
Mort
**(PLEASE REPLACE ALL ABOVE WITH A DETAILED DESCRIPTION OF YOUR PULL REQUEST)** …
> check if the player exists or not, and print informative error message if not

- src/you_get/common.py
- src/you_get/extractor.py
- src/you_get/extractors/bilibili.py
This PR entails a complete rewrite of the `bilibili.py` extractor. The following features are supported by the new extractor. (some URL patterns were already supported by the old extractor, some are new)
1. DASH/m4s streams support. Downloading DASH streams are generally faster than legacy FLV files, and they provide more choices of formats. Relevant format codes are:
* `dash-flv` (1080P)
* `dash-flv720`
* `dash-flv480`
* `dash-flv360`
Note that only relatively newly uploaded videos come with DASH streams, though.
2. Regular Bilibili av videos. If a video page contains multiple parts, you-get will show a warning so that you won't miss any part. Use `-l` to download them all.
Example patterns:
* https://www.bilibili.com/video/av43599036
* https://www.bilibili.com/video/av22195308/?p=3
3. …
> Refactoring of Bilibili extractor

- src/you_get/extractors/facebook.py
> fit "m.facebook.com" and so on

- src/you_get/extractors/acfun.py
AcFun now supported https, thus fix the regular expressions.
> https support for AcFun

- src/you_get/extractors/le.py
letv downloading is not working, it shows
you-get -d http://www.le.com/ptv/vplay/31575401.html#vid=31575401
[DEBUG] url_locations: http://www.le.com/ptv/vplay/31575401.html#vid=31575401
[DEBUG] get_content: http://www.le.com/ptv/vplay/31575401.html#vid=31575401
[DEBUG] get_content: http://player-pc.le.com/mms/out/video/playJson?id=31575401&
platid=1&splatid=101&format=1&tkey=291218714&domain=www.le.com&region=cn&source=
1000&accesyx=1
[DEBUG] get_content: http://play.g3proxy.lecloud.com/vod/v2/MjcxLzI5LzY1L2xldHYt
dXRzLzE0L3Zlcl8wMF8yMi0xMTIzMTk1Njk4LWF2Yy0yMDA0NTktYWFjLTQ4MDAwLTE1MDA0MC00OTAx
ODEwLTI0ZjUxNGZjZGE0Y2NkNTQ1NWFmNTRmNWRiZDhkMjA3LTE1NTYxNjYxNzczNDAubXA0?b=261&m
msid=66965350&tm=1558577950&key=51ab6a57c5f525df0c5a499dea02b146&platid=1&splati …
> letv无法正常下载视频及解决方法

- src/you_get/extractors/sohu.py
sohu downloading is not working, it shows
you-get -d https://tv.sohu.com/v/dXMvMzE4NTE5MjIzLzEzNDU3MjM3OC5zaHRtbA==.html
[DEBUG] get_response: https://tv.sohu.com/v/dXMvMzE4NTE5MjIzLzEzNDU3MjM3OC5zaHRt
bA==.html
[DEBUG] get_response: http://hot.vrs.sohu.com/vrs_flash.action?vid=134572378
you-get: version 0.4.1302, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://tv.sohu.com/v/dXMvMzE4NTE5MjIzLzEzNDU3MjM3OC5za
HRtbA==.html'], auto_rename=False, cookies=None, debug=True, extractor_proxy=Non
e, force=False, format=None, help=False, http_proxy=None, info=False, input_file
=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False,
no_proxy=False, output_dir='.', output_filename=None, password=None, player=None
, playlist=False, socks_proxy=None, …
> sohu短视频无法正常下载及解决办法

- src/you_get/extractors/youku.py
> changed youku ccode to 0519

- src/you_get/extractors/ixigua.py
我發現了這個程式只下載低畫質的ixigua影片
在這裡提出修正
原本程式只擷取video_1的影片，但其實有更高畫質的video_2可以選
> Pick best video quality for ixigua

- src/you_get/extractors/acfun.py
之前的`/video/getVideo.aspx`已经失效，现在改为m3u8方式下载（#2734）。
已测试链接：https://www.acfun.cn/bangumi/ab5024870
> 更新A站番剧下载接口 (Fix #2734)

- README.md
- src/you_get/common.py
- src/you_get/extractors/missevan.py
- tests/test.py
Add support for [MissEvan](https://www.missevan.com/).
Download support:
* single sound and cover (e.g. <https://www.missevan.com/sound/player?id=1285995>)
* drama (e.g. <https://www.missevan.com/mdrama/drama/24130>)
* album (e.g. <https://www.missevan.com/albuminfo/203090>)
> Add support for missevan.com

- src/you_get/common.py
for example, https://coub.com/view/xrbu1
> fix coub with quotes

- src/you_get/extractors/youtube.py
It looks like working well.
#2755 tested.
> fix issue about KeyError: 'url_encoded_fmt_stream_map'

- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/kakao.py
test results
test1 : python3 ./you-get -d https://tv.kakao.com/channel/2681352/cliplink/404022252
test2 : python3 ./you-get -d https://tv.kakao.com/channel/2943001/cliplink/404071971
test3 : python3 ./you-get -d https://tv.kakao.com/channel/2653132/cliplink/300078694
downloaded videos
> add support for tv.kakao.com 

- src/you_get/extractors/acfun.py
- tests/test.py
> fix video download in acfun

- src/you_get/extractors/bilibili.py
fix below bug
1. can't download bilibili VIP bangumi video even loaded cookies which include VIP message, this is caused by didn't take **Referer** message in header when try to get video info
2. modify the height_to_quality() function to make it can resolve 1080P+ video, this is caused by 1080P and 1080P+ video's height is same, so add another prop **qn** to make sure can get correct quality
修复BUG
1. 即使加载了有大会员的cookie依然不能下载
原因：获取信息时未携带**Referer**信息
解决：获取信息时携带**Referer**信息
2. 无法正确获取1080P+视频
原因：1080P和1080P+视频的高度均为1080P
解决：加入**qn**作为判断依据
> bug fix, download bilibili VIP video, resolve 1080P+ video

- src/you_get/extractors/bilibili.py
1. Able to download video from Pth video selected by url from a muti-part video
2. Fix bug on flv only playlist video, sort stream is necessary for it
> Fix bug on flv only playlist video

- src/you_get/extractors/ixigua.py
```
$ ./you-get --debug https://www.ixigua.com/i6695590740761772552/
[DEBUG] get_response: https://www.ixigua.com/i6695590740761772552/
you-get: video_id not found, url:https://www.ixigua.com/i6695590740761772552/
```
> [ixigua] fix error 'video_id not found'

- setup.py
A simple way to make life much easier :)
c.f. `you_get.common.set_socks_proxy`
> Add PySocks as an extra requirement

- src/you_get/extractors/qq.py
尝试通过修改UA下载1080p，但是之前没接触过Python，依葫芦画瓢改了半天重新编译后发现UA还是默认的Python-urllib。
或者有没有UA的命令参数，试了-user-agent报错。
祝新春吉祥，百毒不侵，感谢。
> 设想伪装腾讯视频客户端下载1080P

- src/you_get/extractors/baomihua.py
add request headers
fix urllib.error.HTTPError: HTTP Error 403: Forbidden
> [baomihua] fix download 403

- src/you_get/extractors/bilibili.py
ref https://www.bilibili.com/blackboard/activity-BV-PC.html
> [Bilibili] add support for BVID

- src/you_get/extractors/bilibili.py
Add the missing support for playlist mode.
Thanks https://github.com/soimort/you-get/pull/2781 .
> [Bilibili] add support for BVID in playlist mode of bilibili

- src/you_get/extractors/bilibili.py
> fix bilibili favlist download

- README.md
- src/you_get/common.py
- src/you_get/extractors/__init__.py
- src/you_get/extractors/xinpianchang.py
- tests/test.py
Add Support for [新片场](https://www.xinpianchang.com/a10673220)
```console
$ you-get -i https://www.xinpianchang.com/a10673220
site:                xinpianchang
title:               疫情
- format:        1080
quality:       高清 1080P
size:          8.3 MiB (8730005 bytes)
- format:        720
quality:       高清 720P
size:          3.9 MiB (4108878 bytes)
- format:        540
quality:       清晰 540P
size:          2.5 MiB (2634093 bytes)
- format:        360
quality:       流畅 360P
size:          0.5 MiB (537062 bytes)
```
```console
$ you-get -F=1080 https://www.xinpianchang.com/a10673220
site:                xinpianchang …
```
> Add Support for xinpianchang [新片场]

- src/you_get/extractors/bilibili.py
增加了bilibili新出的4K的支持，增加了quality为120的一档。
> [bilibili]support 4k

- src/you_get/extractors/youtube.py
Hopefully this fixes https://github.com/soimort/you-get/pull/2811.
> [youtube] fix `KeyError: 'url'` on some videos

- src/you_get/common.py
When `url_save` is passed a list of urls (`is_chunked = True`), and the download is aborted, then the next time that you-get resumes the download, it will append the video data from beginning to the `.download` file, because it does not send a correct `Range` header when resuming.
Several "exceeding 100%" issues might be related to this: #2703, #2768
Steps to reproduce:
1. `you-get "https://www.youtube.com/watch?v=Y8Tko2YC5hA"`
2. Press `Ctrl-C` before the download is finished
3. Re-start the `you-get` command
3. The downloaded size will eventually exceed the expected file size and some merging error will appear
<details>
<summary>The transcript for the steps</summary>
```
~/test > you-get "https://www.youtube.com/watch?v=Y8Tko2YC5hA"
site:                YouTube
title:               What …
```
> Fix resuming when downloading in chunked mode

- src/you_get/extractors/pptv.py
> [pptv] fix: download pptv error, code 403 / 405 

- src/you_get/extractors/youku.py
```
you-get https://v.youku.com/v_show/id_XMTI4MDU0MTAzMg==.html
you-get: 客户端无权播放,201
```
To fix the problem, change ccode to 0590
> Update ccode 0590 for Youku

- src/you_get/extractors/mgtv.py
* Use multiple endpoints for info, metadata and content
* Add tk2 and pm2 in request
* Add referer header for download from CDN
* Add playlist support
* Format code
> Fix mgtv download

- src/you_get/extractors/mgtv.py
Also fix indentation causing undefined variable
> #2859 Mgtv: add another format of url

- src/you_get/extractors/missevan.py
- soundurl，高音质，标准链接
- soundurl_128，低音质，标准链接
- cover_image，封面大图，拼接链接
- front_cover，封面小图，标准链接
https://www.missevan.com/sound/player?id=999921
```json
{
"success": true,
"info": {
"sound": {
"id": 999921,
"catalog_id": 48,
"create_time": 1527170055,
"last_update_time": 1527216802,
"duration": 234866,
"user_id": 2941423,
"username": "宁采臣丶在唱歌",
"cover_image": "201805/24/18170f183c26437e385c2c766428d9e2135413.jpg",
"animationid": 0,
"characterid": 0,
"seiyid": 0,
"soundstr": "武林之王的退隐生活",
"intro": "<p>《武林之王的退隐生活》小说/漫画主题曲</p><p>音频见评论区</p><p>原著：Lee太白</p><p>策划：左耳从东</p><p>作词：南岐</p><p>作曲：明遥</p><p>编曲：sea云</p><p>原唱：小坠</p><p>翻唱：宁采臣</p><p>混音：小语</p><p>PV：Bung Kon</p><p>素材：《武林之王的退隐生活》漫画</p><p>出品：SF轻小说  合火人工作室</p><p>（感言部分可以自由发挥啦~）</p><p><br /></p>",
"soundurl": …
```
> feat: 适配猫耳 FM 新版 API

- src/you_get/extractors/miaopai.py
match urls like `https://h5.video.weibo.com/show/1034:xxx` and `https://weibo.com/tv/show/1034:xxx`
example:
```
def test_miaopai(self):
miaopai.download("https://weibo.com/tv/show/1034:4611434789928964?from=old_pc_videoshow", info_only=True)
def test_miaopai2(self):
miaopai.download("https://h5.video.weibo.com/show/1034:4611434789928964", info_only=True)
```
output:
```
Site:       miaopai
Title:      鬼知道我又看了几遍
Size:       6.36 MiB (6670664 Bytes)
```
> [miaopai] fix weibo videos with h5 api

- .github/workflows/python-package.yml
- you-get.json
“3.10” must be quoted or yaml will treat it as 3.1.
> Test on Python 3.10

- src/you_get/extractors/zhihu.py
Reference: https://help.doxy.me/en/articles/1160727-video-resolution-change-definition-during-a-call
> Fix zhihu extractor comment: ld

- src/you_get/extractors/bilibili.py
- tests/test.py
Download playlist from bilibili.com. 
Url pattern: https://space.bilibili.com/<mid>/channel/seriesdetail?sid=<sid>
> support channel/series for bilibili

- src/you_get/extractors/bilibili.py
error msg: Key: 'SearchArg.Ps' Error:Field validation for 'Ps' failed on the 'lte' tag
> update space_video_api arg: page size

- src/you_get/common.py
> Fixed a typo

- src/you_get/extractors/missevan.py
1. Get size returned 403 if headers was empty
2. Get container returned query and fragment from url
> [missevan] Fix getting info

- src/you_get/extractors/bilibili.py
Added support of collectiondetail api of bilibili, tested works with -l option 
`./you-get --format=flv360 -l https://space.bilibili.com/364152971/channel/collectiondetail?sid=13909`
There is already a pull request for the test code: https://github.com/soimort/you-get/pull/2958 @soldatjiang
> added support to bilibili collectiondetail api

- src/you_get/processor/ffmpeg.py
isync this option is deprecated and does nothing
> Update ffmpeg.py remove option "isync"

- src/you_get/extractors/bilibili.py
> [bilibili] api url update.

- src/you_get/extractors/twitter.py
> [twitter] fix twitter video download

- MANIFEST.in
Looks like couple of files are missing in the pypi sdist, so update manifest.in to include them.
relates to https://github.com/Homebrew/homebrew-core/pull/175438
> chore: update `MANIFEST.in` to include missing files
