soimort/you-get

src/you_get/common.py
This PR converts the output of, for instance,
you-get -u http://v.youku.com/v_show/id_XNzIwOTA1OTI4.html
from
```
site:                优酷 (Youku)
title:               Apple Special Event, WWDC 2014 Keynote
stream:
- format:        flv
video-profile: 标清
size:          267.4 MiB (280408659 bytes)
Real URLs:
['http://112.25.17.177/6776355EA734E795D43212134/0300021500538D0AE76B4201AD1C894E56C696-E608-436D-E978-2C85541FFAAA.flv', 'http://112.25.51.42/6979500DA693C773493E166B4/0300021501538D0AE76B4201AD1C894E56C696-E608-436D-E978-2C85541FFAAA.flv', 'http://112.25.47.45/6576355E6763D7752E82D4F67/0300021502538D0AE76B4201AD1C894E56C696-E608-436D-E978-2C85541FFAAA.flv', 'http://112.25.47.23/6779500D7DC3C7733A3805A4D/0300021503538D0AE76B4201AD1C894E56C696-E608-436D-E978-2C85541FFAA …
```
=> Print URLs one per line instead of as a list when the --url option is specified

src/you_get/extractors/iqiyi.py
- Fix #569 for new player:
- http://www.iqiyi.com/common/flashplayer/20150710/MainPlayer_5_2_25_c3_3_5_1.swf
- Extract `tvid` and `vid` from embeded URLs such as:
- http://www.iqiyi.com/common/qplay.html?cnid=5&tvid=4087092609&vid=049fe2ee97bf72f4ef7c30b85ae2c251
We need a way to automatically extract keys from its player...
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/570)
=> Fix iqiyi (20150710)

src/you_get/extractors/bilibili.py
当有多 P 时，会错误的将 1P 的 id 重复加入 list。
测试地址：
http://www.bilibili.com/video/av824538/
http://www.bilibili.com/video/av2772797/
fix #497
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/610)
=> fix duplicate url bug for bilibili

src/you_get/extractors/dailymotion.py
Some videos that use lower resolutions do not work for me.
Here is an example: www.dailymotion.com/video/x2mzuat
The fix is quite simple (arguably, using get() instead of [] inside try-catch might be better).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/618)
=> Fix problems with videos that do not have 720p mode

src/you_get/extractors/yinyuetai.py
The JSON API suggested in #559 is bound to region restriction. e.g.,
* http://ext.yinyuetai.com/main/get-h-mv-info?json=true&videoId=2356333 (inaccessible outside mainland China)
* **A better API**: http://www.yinyuetai.com/insite/get-video-info?json=true&videoId=2356333 (accessible overseas)
This PR will enable downloading the best qualityLevel possible (`sh`).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/625)
=> [YinYueTai] Switch to JSON API

src/you_get/extractors/vimeo.py
Note the rate limit of the API key.
```
python3 you-get https://vimeo.com/channels/464686
Video Site: Vimeo.com
Title:      8.4 Recursion with Transformations (The Nature of Code) from shiffman on Vimeo
Size:       130.77 MiB (137121450 Bytes)
Downloading 8.4 Recursion with Transformations (The Nature of Code) from shiffman on Vimeo.mp4 ...
```
There are too many videos to test, but according to the API everyone should be working.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/634)
=> Add Vimeo Channel support, fix #121

src/you_get/extractors/youku.py
Youku playlist can have multiple pages, for example: http://www.youku.com/playlist_show/id_22394567.html
Currently we only deal with the first page. And it's not even possible to download the second page via the complete url, for example: http://www.youku.com/playlist_show/id_22394567_ascending_1_page_2.html
Because we always try to extract the playlist id from the url and then download the first page.
With this pull request, we will download all videos from the playlist.
Tested by running the following command locally and make sure the output has all videos included.
you-get -i http://www.youku.com/playlist_show/id_22394567.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/645)
=> [youku] support multi-page playlists

src/you_get/extractors/youku.py
TL;DR: When downloading a playlist, a single failure shouldn't terminate the whole process.
Youku playlist can have broken video links. I believe this happens really rare, but I have one sample here: http://www.youku.com/playlist_show/id_21492543.html
This playlist contains a broken video link: http://v.youku.com/v_show/id_XNjUxNzQyNzEy.html
Since python set is unordered, when downloading this playlist, we can hit this video at a random point of the whole process, and crash.
This diff is just a rough idea. I'm open for opinions. I have several in my mind actually:
Should we have a flag guarding this feature?
Should we apply this feature to all extractors? If yes is there a better way to do that other than changing every extractor that support playlist?
[<img …
=> [youku] gracefully handle single failure when downloading playlist

src/you_get/processor/ffmpeg.py
This fixes `RuntimeError: No active exception to reraise`. Raising a `CalledProcessError` is more useful for debugging and manual fixing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/678)
=> [ffmpeg] use subprocess.check_call

src/you_get/extractors/acfun.py
```
λ  you-get-develop [develop] ./you-get -i http://www.acfun.tv/v/ac2224547
File "./you-get", line 19, in <module>
File "/home/soimort/Projects/you-get-develop/src/you_get/__main__.py", line 91, in main
main()
File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 1152, in main
script_main('you-get', any_download, any_download_playlist)
File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 966, in script_main
download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
File "/home/soimort/Projects/you-get-develop/src/you_get/common.py", line 851, in download_main
download(url, **kwargs)
File …
```
=> [Acfun] Fix "unexpected keyword argument 'json_output'"

src/you_get/common.py, src/you_get/extractors/bilibili.py
Reverts soimort/you-get#610, as it caused a regression bug #688. To reproduce:
```
λ  you-get-develop [develop] ./you-get -i http://www.bilibili.com/video/av2537307/index_11.html
Video Site: bilibili.com
Title:      【MJSK4字幕组】真假學園4 外伝1-12 蓝光版合集(11)
Size:       762.03 MiB (799042740 Bytes)
```
The 11th partition is omitted.
```
λ  you-get-develop [develop] ./you-get -i http://www.bilibili.com/video/av2537307/index_12.html
Video Site: bilibili.com
Title:      【MJSK4字幕组】真假學園4 外伝1-12 蓝光版合集(12)
Size:       753.12 MiB (789705477 Bytes)
```
The 12th partition is omitted.
The real size of the video should be 12P in 832.38 MiB (872816678 Bytes).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
=> Revert "fix duplicate url bug for bilibili"

src/you_get/common.py, src/you_get/extractors/bilibili.py
The old-fashioned Netscape `cookies.txt` is nowhere to be seen in modern browsers. We should really move on to a modern format (e.g. Mozilla's SQLite-based cookies), so there will be no need for one to manually export `cookies.txt` anymore.
Also, this will allow for easier downloads of Bilibili's member-only videos, just grab a cookie file from your Firefox:
```
$ you-get -i -c ~/.mozilla/firefox/gggfz9xl.default/cookies.sqlite \
http://www.bilibili.com/video/av2987444
```
Bilibili uses CAPTCHA verification as part of its login process, so there is no way to automatize this like we do in Niconico. Preloading existed cookies is a must in such occasions.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/6 …
=> Load Mozilla cookies.sqlite

src/you_get/extractor.py, src/you_get/extractors/youtube.py
Download YouTube videos together with subtitles / closed captions.
Since YouTube (also Google Video) uses its own non-standard XML format for storing timed text, and that is hardly ever supported by any media player, all downloaded captions will be converted to [SRT subtitle format](http://www.matroska.org/technical/specs/subtitles/srt.html) automatically.
(Fix #36, #235)
Example:
```
λ  you-get-develop [youtube-caption-tracks] you-get --itag=137 youtu.be/8r7SGQ4c4fQ
site:                YouTube
title:               【MV】Green Flash / AKB48[公式]
stream:
- itag:          137
quality:       1920 x 1080
size:          86.6 MiB (90798818 bytes)
Downloading 【MV】Green Flash - AKB48[公式].mp4 ...
100.0% ( 86.6/86.6 MB) [========================================] 2/2
Merging video …
```
=> [YouTube] Download subtitles / closed captions in SRT format

src/you_get/extractors/embed.py
For some pages such like http://www.pideo.net/video/youku/8cbc48e546ea657a/, a single embedded pattern appears in the page multiple times. Should only download each URL once.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/711)
=> Don't download duplicated URLs in embed.py

src/you_get/common.py, src/you_get/extractors/universal.py
Fix #65 and #99.
From now on, the dumb `NotImplementedError` is gone. Here's a better fallback: try to extract all possible video URLs from any unknown video site.
This naive approach turns out to be pretty useful. I find it handy for supporting sites like these:
* xvideos
* xhamster
* thisav
* youporn
* toukoucity
* adultcity
and a bunch more.
(I didn't want my `extractors` folder filled with those, but y'all know there's a key for every lock...)
Having typed "`you-get`" in the terminal so often that I sometimes misused the command where it should be "`wget`". Now we can actually use `you-get` in place of `wget`:
```
$ you-get https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
```
And my favorite recurrence thing, `you-get` gets `you-get` itself:
```
$ you-get …
```
=> Universal extractor

src/you_get/common.py, src/you_get/extractors/baidu.py
So we don't have to click on the external link to redirect to Youku or Tudou.
Tested on:
- http://tieba.baidu.com/p/4111285036
- http://tieba.baidu.com/p/3761393244?see_lz=1
I once wrote an [image scraper](https://github.com/soimort/resave/blob/master/resave.tcl) to do this, but it's in Tcl, a creepy 1990s scripting language. Now let's get started with Python!
- http://tieba.baidu.com/p/4111154068?see_lz=1
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/717)
=> [贴吧] Download embedded videos and images

README.md, src/you_get/common.py, src/you_get/extractors/__init__.py, src/you_get/extractors/veoh.py
```
python3 you-get http://www.veoh.com/watch/v31095531C9r4dFkG
Site:       Veoh
Title:      Japan all-girl group ad 'encourages homosexuality'
Size:       1.22 MiB (1276115 Bytes)
Downloading Japan all-girl group ad 'encourages homosexuality'.mp4 ...
```
```
python3 you-get --json http://www.veoh.com/m/watch.php?v=v31095531C9r4dFkG&quality=1
{
"site": "Veoh",
"streams": {
"__default__": {
"container": "mp4",
"size": null,
"src": [
"http://content.veoh.com/flash/p/2/v31095531C9r4dFkG/h31095531.mp4?ct=aa63fcf606b2374b41765e4b8e75759310e70cece41fc6f2"
],
"video_profile": "__default__"
}
},
"title": "Japan all-girl group ad 'encourages homosexuality'",
"url": null
}
```
百合啊百合（
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on …
=> Add Veoh support, fix #79

src/you_get/extractors/facebook.py
Hey! When I'll make a download of some video from facebook I get the following output:
```shell
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
```
Certainly, facebook has been updated and a new key must be inserted. This PR will fix the error.
Try it yourself with any url video from facebook.
hugs.
[<img …
=> Added new key on facebook extractor

src/you_get/extractors/instagram.py
When I try to download the video from [here][1] or any other url, it gives me the following output:
```
Site:       Instagram.com
Title:      Futbol ▪ Soccer ▪ Football ⚽🏆 on Instagram: “Que tapa do Marquinhos Gabriel! 👏 Via: @santosfc” [9Z7TJKJURs]
Size:       1.95 MiB (2041236 Bytes)
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this …
```
=> Fix bug on Instagram Extractor

src/you_get/extractors/miomio.py
Hi! When I try to download a video from miomio, get the following output.
```
INSERT ❯ you-get --debug http://www.miomio.tv/watch/cc247040/
you-get: version 0.4.125, a tiny downloader that scrapes the web.
you-get: ['http://www.miomio.tv/watch/cc247040/']
File "/usr/local/opt/pyenv/versions/3.4.2/bin/you-get", line 11, in <module>
sys.exit(main())
File "/usr/local/opt/pyenv/versions/3.4.2/lib/python3.4/site-packages/you_get/__main__.py", line 92, in main
main(**kwargs)
File "/usr/local/opt/pyenv/versions/3.4.2/lib/python3.4/site-packages/you_get/common.py", line 1213, in main
File "/usr/local/opt/pyenv/versions/3.4.2/lib/python3.4/site-packages/you_get/common.py", line 1134, in …
```
=> Fix bug on MioMio Extractor

src/you_get/common.py, src/you_get/extractors/__init__.py, src/you_get/extractors/fc2video.py
How could this project survive without customizing Headers?
Now Able to call with
```
download_urls([video_url], title, ext, size, output_dir, merge=merge, headers = fake_headers)
```
and everywhere where you can use Faker.
```
python3 you-get   --debug  http://video.fc2.com/en/content/20151021bTVKnbEw
Site:       FC2Video
Title:      ハーメルン市街地
Size:       37.01 MiB (38806848 Bytes)
Downloading ハーメルン市街地.flv ...
2.7% (  1.0/37.0 MB) ├█─────────────────────────────────────┤[1/1]  896 kB/s
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/785)
=> [FC2Video] Add support, fix #102 ; Add custom header support on most of the download-related functions

src/you_get/extractors/zhanqi.py
Also some PEP8.
I am willing to see some REAL fix of WsSecret. Should we can find this algorithm, this would be useful to other sites including Bilibili, maybe Sina...
```
python3 you-get --debug http://www.zhanqi.tv/heroesofthestorm
Site:       zhanqi.tv
Title:      黄金风暴联赛胜者组EDG vs ESTAR
Call rtmpdump:
rtmpdump -r rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//8855_uUA6t -o ./黄金风暴联赛胜者组EDG vs ESTAR.flv
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO:   Server                NGINX RTMP (github.com/arut/nginx-rtmp-module)
INFO:   width                 1280.00
INFO:   height                720.00
INFO: …
```
=> [ZhanQi]temporary fix using RTMP url, bypass to fix #809

src/you_get/common.py, src/you_get/extractor.py, src/you_get/extractors/bilibili.py, src/you_get/extractors/netease.py
Fix #861.
The `--no-caption` option suppresses the download of captions (danmaku, lyrics, subtitles) from
* Bilibili
* music.163.com
* YouTube (see also <https://github.com/soimort/you-get/pull/705#issuecomment-159485291>)
Example:
````console
$ you-get http://www.bilibili.com/video/av3535049/
Site:       bilibili.com
Title:      义薄云天！小女孩为了救自己的朋友，捐肝脏死于手术台
Size:       113.04 MiB (118531404 Bytes)
Skipping ./义薄云天！小女孩为了救自己的朋友，捐肝脏死于手术台.mp4: file already exists
Downloading 义薄云天！小女孩为了救自己的朋友，捐肝脏死于手术台.cmt.xml ...
```
```console
$ you-get --no-caption http://www.bilibili.com/video/av3535049/
Site:       bilibili.com
Title:      义薄云天！小女孩为了救自己的朋友，捐肝脏死于手术台
Size:       113.04 MiB (118531404 Bytes)
Skipping …
```
=> New option: --no-caption

src/you_get/processor/ffmpeg.py
I also met this error message from ffmpeg:
```
[mp4 @ 0x562afd33f380] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
```
Adding the mentioned option fixes the conversion. But I don't know whether we should add this option into you-get.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/899)
=> [ffmpeg] more check_call replacing wrong 'raise's

src/you_get/common.py, src/you_get/extractors/netease.py
网易云音乐的cdn一直在升级，先前提交的pll https://github.com/soimort/you-get/pull/908  已经失效（返回 timeout），但是可以通过修改m为p的方法获取 `headers` 和下载，但是获取的 `headers` 是不存在的 `image/jpg; charset=UTF-8'` ，所以对文件类型做了些修改。
* 使用 m5.music.126.net 解析：
```py
you-get: version 0.4.266, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/song?id=190449']
File "D:\Documents\GitHub\you-get\you-get", line 11, in <module>
File "D:\Documents\GitHub\you-get\src\you_get\__main__.py", line 92, in main
main(**kwargs)
File "D:\Documents\GitHub\you-get\src\you_get\common.py", line 1244, in main
File "D:\Documents\GitHub\you-get\src\you_get\common.py", line 1165, in script_main …
```
=> fix m5.music.126.net return 404

src/you_get/extractors/miaopai.py
```
$ you-get -d  -i 'http://video.weibo.com/show?fid=1034:01ab1ca13b71d4761314f4cf87c01884'
Site:       miaopai
you-get: version 0.4.245, a tiny downloader that scrapes the web.
you-get: ['http://video.weibo.com/show?fid=1034:01ab1ca13b71d4761314f4cf87c01884']
File "/usr/local/bin/you-get", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
main(**kwargs)
File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1237, in main
File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1158, in script_main
download_main(download, download_playlist, args, playlist, output_dir=output_dir, …
```
=> Fix 秒拍部分视频标题包含换行符等，导致正则匹配异常的bug

src/you_get/extractors/yixia.py
The ```scid``` can be anything.
```
Beining$ python3 you-get --debug 'http://www.miaopai.com/show/5Xc1RSi~ULreqXzqWyPz2A__.htm'
Site:       Yixia
Title:      一个工科妹子和她的废柴发明 微博@爷爱怀旧 #搞笑#
Size:       8.32 MiB (8727649 Bytes)
Downloading 一个工科妹子和她的废柴发明 微博@爷爱怀旧 #搞笑#.mp4 ...
0.0% (  0.0/  8.3MB) ├─────────────────────────────────────────┤[1/1] ^C]
```
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/927)
=> [YIxia-Miaopai] Fix #926

src/you_get/extractors/qq.py
Update the url of get  QQ video info, for fix the old url can't download some videos. eg:
```
$ you-get -d -i 'http://v.qq.com/cover/o/omcczahf3t2sye4/l0019czh4pr.html'
you-get: version 0.4.293, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/cover/o/omcczahf3t2sye4/l0019czh4pr.html']
File "/usr/local/bin/you-get", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
main(**kwargs)
File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1250, in main
File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1171, in script_main
download_main(download, download_playlist, …
```
=> [QQ] update the url of get video info

src/you_get/extractors/acfun.py
```
$ you-get -d http://www.acfun.tv/v/ac716001
site:                优酷 (Youku)
title:               【N.G.Z.K-46字幕】130623 乃木坂って、どこ？ep89 子供相談室
stream:
- format:        hd2
video-profile: 超清
size:          215.2 MiB (225627355 bytes)
Downloading 【N.G.Z.K-46字幕】130623 乃木坂って、どこ？ep89 子供相談室.flv ...
100% (215.2/215.2MB) ├███████████████████████████████████████████┤[8/8]    1 MB/s
Merging video parts... Done.
you-get: version 0.4.296, a tiny downloader that scrapes the web.
you-get: ['http://www.acfun.tv/v/ac716001']
File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
main(**kwargs)
File …
```
=> [AcFun] Fix unintended exception when caption not present

src/you_get/extractors/google.py
When a Google+ post contains multiple photos, `you-get` should download them all instead of just the first one.
```console
$ you-get -di https://plus.google.com/+ChrisLord/posts/MCn6XgXSzSp
Site:       Google.com
Title:      2016-01-29_MCn6XgXSzSp
Type:       JPEG Image (image/jpeg)
Size:       0.24 MiB (246744 Bytes)
$ you-get https://plus.google.com/107241677527739013868/posts/FRokFB1ytCi
Site:       Google.com
Title:      2016-02-27_FRokFB1ytCi
Type:       Portable Network Graphics (image/png)
Size:       0.82 MiB (864494 Bytes)
Downloading 2016-02-27_FRokFB1ytCi.png ...
100% (  0.8/  0.8MB) ├███████████████████████████████████████████┤[1/1]   26 MB/s
```
TODO: currently we don't handle ajax, so the maximum number of photos we get at once (achieved from an HTML page) is 4. Also, there …
=> [Google+] Get multiple photos

README.md, src/you_get/common.py, src/you_get/extractors/__init__.py, src/you_get/extractors/infoq.py
You can download InfoQ presentations, MP3 or slides as you like (without having an account)
Example: [[1]](http://www.infoq.com/presentations/lmdb-lighting-memory-mapped-database)
```console
$ you-get -di http://www.infoq.com/presentations/lmdb-lighting-memory-mapped-database
site:                InfoQ
title:               The Lightning Memory-mapped Database
- format:        video
size:          327.6 MiB (343479057 bytes)
- format:        audio
container:     mp3
size:          53.3 MiB (55854710 bytes)
- format:        slides
container:     pdf
size:          1.1 MiB (1119614 bytes)
```
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on …
=> Add support for InfoQ

src/you_get/extractors/iqiyi.py
There is [a video](http://www.iqiyi.com/v_19rrkviljg.html) on iQiyi, the title of which contains some Unicode special characters: http://www.fileformat.info/info/unicode/char/200B/index.htm
Although it won't cause any problem on Linux / OS X, it doesn't fit into the GBK codepage and will lead to confusions for Windows users, especially those who are not aware how Windows sucks on dealing with multi-language encoding (#949, #952)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/953)
=> [iqiyi] Strip Unicode character '\u200b'

src/you_get/extractors/youtube.py
Obviously some YouTube videos require a login for age confirmation. Luckily, restrictions as such can be easily bypassed (unlike country/region restriction).
```console
$ you-get -di 'https://www.youtube.com/watch?v=CMpBT5iG4nU'
you-get: version 0.4.322, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=CMpBT5iG4nU']
File "./you-get", line 11, in <module>
File "./src/you_get/__main__.py", line 92, in main
main(**kwargs)
File "./src/you_get/common.py", line 1257, in main
File "./src/you_get/common.py", line 1178, in script_main
download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, …
```
=> [YouTube] Bypass age restriction

src/you_get/common.py
There has been many times users report issues about `UnicodeEncodeError`, when they're trying to download a video with some non-Latin characters in its title, but the system locale does not actually has the required charset.
Clearly not everyone wants to read the [FAQ](https://github.com/soimort/you-get/wiki/FAQ), so there has to be a better way to give instructions to users. Here it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/974)
=> Catch UnicodeEncodeError and ask users to change the locale

src/you_get/extractor.py
you-get URL1 URL2 时，如果URL1和URL2是同一个网站，并且这个网站的解析是用VidoeExtractor来实现的。
download_by_url 不会更新vid，vid总是第一个链接的vid。
所以必须重置vid.
同理download_by_vid不会更新url。
to fix https://github.com/soimort/you-get/issues/906
**(请将本内容完整替换为PULL REQUEST的详细内容)**
when use xxx_download_by_url(url1/url2)
vid will not reset, only first url will download
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/977)
=> reset url and vid when download in serial

src/you_get/extractors/dilidili.py
I am using the latest ```ckplayer``` to do the extracting.
I am thinking should we have TAPS sometime in the future, this would reduce a lot of works.
I am still having some problems with sources at Tudou, like http://www.dilidili.com/watch/9901/ . But I cannot play it anyway from my side. 
```
python3 you-get --debug http://www.dilidili.com/watch/27625/
Site:       CKPlayer General
Title:      Schwarzesmarken死亡黑标 第3话 第3话
Size:       205.79 MiB (215785120 Bytes)
Downloading Schwarzesmarken死亡黑标 第3话 第3话.flv ...
0.0% (  0.0/205.8MB) ├─────────────────────────────────────────┤[1/8] ^C
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/990 …
=> [dilidili]Repair, Fix #987, close #986 

src/you_get/common.py
I know this PR is unsolicited and may be controversial (especially in terms of implementation), but the undeniable fact is currently the `--debug` option doesn't live up to its name. It only enables a traceback upon failure, which is useless most of the time (at least for me) without dropping into a debugger.
Most errors I have ever encountered occur at the extraction stage, so it's essential to know the URLs that you-get is trying to retrieve and parse in order to determine why it fails to do so. It also helps to know what's being retrieved in the case of zero failure yet seemingly hanging forever (happens to me often enough — connection to Mainland is really bad). AFAIK `get_content` is the most common and non-deprecated function used in the extraction stage, so in this PR I'm printing …
=> Enhanced debug logging: Print URL of get_content call when --debug is enabled

src/you_get/extractors/bilibili.py
If a video has multiple parts, it doesn't make much sense for `you-get` to download only the 1st part (which is the current behavior). Instead, all parts (if available) should be downloaded by default.
If you have the need for downloading one single part of videos, feel free to comment here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1019)
=> [Bilibili] Download multi parts (changing default behavior)

src/you_get/extractors/dilidili.py
```
python3 you-get --debug http://www.dilidili.com/watch/3539/
[DEBUG] get_content: http://www.dilidili.com/watch/3539/
[DEBUG] get_content: https://player.005.tv:60000/?vid=XNTM1OTgxMjYw&v=youku&sign=602f02e01e9eb5e50010eb8d02a68aa4
[DEBUG] get_content: http://player.005.tv/parse.php?xmlurl=null&type=youku&vid=XNTM1OTgxMjYw&hd=2&sign=602f02e01e9eb5e50010eb8d02a68aa4&tmsign=3e2408856fae07b443098d72a6e75359&userlink=http%3A%2F%2Fwww.dilidili.com%2F
[DEBUG] get_content: http://player.005.tv/parse.php?xmlurl=null&type=youku&vid=XNTM1OTgxMjYw&hd=3&sign=602f02e01e9eb5e50010eb8d02a68aa4&tmsign=3e2408856fae07b443098d72a6e75359&userlink=http%3A%2F%2Fwww.dilidili.com%2F
Site:       CKPlayer General
Title:      银魂 第239话「忘年会上仍有不可忘记的事物」
Size:       212.89 MiB …
```
=> [Dilidili] Fix codec, fix #1085

src/you_get/extractors/bandcamp.py
This fixes the exception:
File "you-get/lib/python3.4/site-packages/you_get/extractors/bandcamp.py", line 9, in bandcamp_download
trackinfo = json.loads(r1(r'(\[{"video_poster_url".*}\]),', html))
File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
s.__class__.__name__))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1097)
=> bandcamp: Sometimes the first key is video_caption

src/you_get/extractors/tucao.py
Fix the tucao extractor.
The domain of Tucao is changed from tucao.cc to tucao.tv. And the recent uploading videos are all using 189 video source type, which are not supported by previous method. Just fix these issues.
Some test links,
189 source
``` 
you-get --debug http://www.tucao.tv/play/h4063381/
[DEBUG] get_content: http://www.tucao.tv/play/h4063381/
Site:       tucao.tv
Title:      【4月】hundred 百武装战记  03话【恶魔岛】
Type:       Unknown type (None)
Size:       197.77 MiB (207378126 Bytes)
Downloading 【4月】hundred 百武装战记  03话【恶魔岛】.mp4 ...
100% (197.8/197.8MB) ├██████████████████████████████████████████████████████████████┤[1/1]    2 MB/s 
```
sina source
```
you-get --debug http://www.tucao.tv/play/h116/
[DEBUG] get_content: http://www.tucao.tv/play/h116/ …
```
=> [Tucao] fix url and add support to 189 video source

src/you_get/extractors/dilidili.py
I am very sorry that I commit a wrong code yesterday.
Now, it should be fixed.
It means to match `http://www.dilidili.com/watch3/37348/` and `http://www.dilidili.com/watch/29976` which is different from 'watch/' and 'watch3/'.
My test:
```
you-get -p mpv http://www.dilidili.com/watch3/37348/
Site:       CKPlayer General
Title:      我叫坂本我最屌 第4话 坂本是臭流氓吗？
Size:       184.63 MiB (193598554 Bytes)
```
```
you-get -p mpv http://www.dilidili.com/watch/29976/
Site:       CKPlayer General
Title:      Legal High 第1集
Size:       703.8 MiB (737990733 Bytes)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/11 …
=> fix the url 'watch/' and 'watch3/' error

README.md, src/you_get/common.py, src/you_get/extractors/__init__.py, src/you_get/extractors/panda.py
some test:
```
$ you-get http://www.panda.tv/11175
Site:       panda.tv
Title:      解说米勒：6.9版本无敌上分套路
Downloading 解说米勒：6.9版本无敌上分套路.flv ...
0.0% ( 70.2/  infMB) ├────────────────────────────────────────────────┤[1/1]  241 kB/s
```
```
$ you-get -i http://www.panda.tv/11175
Site:       panda.tv
Title:      解说米勒：6.9版本无敌上分套路
```
```
$ you-get --json http://www.panda.tv/11175
{
"site": "panda.tv",
"streams": {
"__default__": {
"container": "flv",
"size": null,
"src": [
"http://pl3.live.panda.tv/live_panda/ff219f7a58fe290ef8e39e7df4986f7c.flv"
],
"video_profile": "__default__"
}
},
"title": "解说米勒：6.9版本无敌上分套路",
"url": null
}
```
---
This change is [<img …
=> add support Panda.tv

src/you_get/common.py
After a successful merge, print `Merged into <filename>` instead of just `Done.`.
The rationale for this is that the `Downloading <filename> ...` message could be confusing because the extension given there is usually not the extension in the final merged file (see `get_output_filename` for extension mapping), so it's worthwhile to communicate to the user what the actual output file is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1128)
=> Print merged filename after successful merge

README.md, src/you_get/common.py, src/you_get/extractors/__init__.py, src/you_get/extractors/naver.py
Korean famous streaming site: http://tvcast.naver.com
test URL: http://tvcast.naver.com/v/879521
```console
python3 you-get -d http://tvcast.naver.com/v/879521
Site:       tvcast.naver.com
Title:      세호야! 여기는 왔어야지
Size:       92.54 MiB (97037489 Bytes)
Downloading 세호야! 여기는 왔어야지.mp4 ...
100% ( 92.5/ 92.5MB) ├██████████████████████████████████████████████████┤[1/1]  188 kB/s
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1143)
=> add Naver support

src/you_get/common.py
To workaround #1155, I've implemented automatic retry if the request timeout after 10 seconds.
It works pretty well for me.
```
C:\Users\JayXon\Documents\GitHub\you-get (develop)
λ python you-get -d -o d: http://www.youku.com/show_page/id_z3411ef989cc211e5b2ad.html
[DEBUG] get_content: http://www.youku.com/show_episode/id_z3411ef989cc211e5b2ad
site:                优酷 (Youku)
playlist:            None
videos:
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTQxNDgxODc4OA==&ct=10
[DEBUG] request attempt 1 timeout
[DEBUG] request attempt 2 timeout
[DEBUG] request attempt 3 timeout
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTQxNDgxODc4OA==&ct=12
[DEBUG] request attempt 1 timeout
[DEBUG] request attempt 2 timeout …
```
=> Retry request if timeout in get_content

you-get
```bash
ln -s /path/to/you-get/you-get /usr/local/bin/you-get
```
execute you-get will get error
```python
➜  ~ you-get
File "/usr/local/bin/you-get", line 9, in <module>
import you_get
ImportError: No module named 'you_get'
```
use os.path.dirname(os.path.realpath(\_\_file\_\_)) get the soft link's real path to fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1169)
=> fix path error

src/you_get/extractors/videomega.py
Since it does UA sniffing now, the implementation of `videomega.py` has to be switched from `VideoExtractor` back to plain `download_urls`. Oldie but goodie.
```
$ you-get -di 'http://videomega.tv/?ref=QLFRB3LTK66KTL3BRFLQ'
[DEBUG] get_content: http://videomega.tv/view.php?ref=QLFRB3LTK66KTL3BRFLQ
you-get: version 0.4.431, a tiny downloader that scrapes the web.
you-get: ['http://videomega.tv/?ref=QLFRB3LTK66KTL3BRFLQ']
File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
main(**kwargs)
File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1291, in main
script_main('you-get', any_download, any_download_playlist, …
```
=> [Videomega] Fix support

README.md, contrib/completion/_you-get, contrib/completion/you-get-completion.bash, contrib/completion/you-get.fish
See original discussion in #1178. I also wrote Bash and Fish completions for the sake of completeness.
---
Paths of completion definitions in this repo are inconsequential, and I don't know a convention for that, so I just modelled it on [git.git](https://github.com/git/git/tree/master/contrib/completion). What's different here is that instead of using a uniform naming scheme for each file (`you-get-completion.<shellname>`), I'm using the conventional name for each shell, which means `_you-get` for Zsh, for instance. Users of each shell should be able to pick out the completion definition for their shell based on the filenames; in the worst case, they can still tell from the comment at the top of each file.
Note that I'm no expert on Bash or Fish completion, so `you-get-completion.bash` …
=> Add shell completion definitions for Bash, Fish and Zsh

src/you_get/common.py
This is to enable socks proxy like shadowsocks. I added options -s and --socks-proxy to specify socks proxy. The patch depends on PySocks (imported only when --socks-proxy is specified). Tested with Youtube and works fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1231)
=> enable socks5 proxy like shadowsocks

src/you_get/common.py, src/you_get/extractors/__init__.py, src/you_get/extractors/showroom.py
Let it rain.
```
$ python3 you-get --debug https://www.showroom-live.com/62ca1628936
[DEBUG] get_content: https://www.showroom-live.com/62ca1628936
[DEBUG] get_content: https://www.showroom-live.com/api/live/streaming_url?room_id=62565&_=1467349598375
[DEBUG] get_content: https://www.showroom-live.com/api/room/profile?room_id=62565
Site:       Showroom
Title:      みかん色の愛を君に…♡
Type:       Unknown type (None)
Size:       0.0 MiB (150 Bytes)
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://52.69.84.185:1935/liveedge/fce6e36abcbf9c73f06bd6c21320a7e4f8d6930966ab3a3686959ad050f54cac/playlist.m3u8 -c copy -bsf:a aac_adtstoasc みかん色の愛を君に…♡.mp4
ffmpeg version 3.0.2 Copyright (c) 2000-2016 the FFmpeg developers
built with Apple LLVM version 7.3.0 …
```
=> [Showroom] Add support via HLS M3U, fix #1218

src/you_get/extractors/facebook.py
Commit 13dc2e9d61dee1db5a7e843a5c1d24c4dca4309d that fixed #1203 dropped `hd_src`, so many videos were no longer available in their best possible quality (720p). Now HD download is back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1242)
=> [Facebook] use hd_src whenever possible

src/you_get/extractors/iqiyi.py
I don't like the code I wrote, especially working in a weather > 30 °C.
But it works:
```
$ python3 you-get --debug http://www.iqiyi.com/v_19rrne7134.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/304454700/4ae17335b6d0c0283d4f29129927a8d2/?t=1467936544580&sc=3d320f9133696f45b28f08949a028169&src=76f90cbd92f94a2e925d83e8ccd22cb7
site:                爱奇艺 (Iqiyi)
title:               刘宇珽 
stream:
- format:        BD
container:     m3u8
video-profile: 1080p
size:          0.0 MiB (0 bytes)
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://cache.m.iqiyi.com/dc/dt/3ff73fa4x20048e50x777a6171/20140917/05/1b/37df9290540397d04a1b357d9a42dbf3.m3u8?qd_sc=fa25a2ff4675331ac255340d799e28f6&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-304454700_04022000 …
```
=> [iQiyi] Use FFmpeg to record M3U file

src/you_get/extractors/showroom.py
When a show has not started yet, `you-get` summarily fails with an error message:
```console
$ yg -di https://www.showroom-live.com/48_Rena_Kato
[DEBUG] get_content: https://www.showroom-live.com/48_Rena_Kato
[DEBUG] get_content: https://www.showroom-live.com/api/live/streaming_url?room_id=61567&_=1468130011718
you-get: Cannot find any live URL! Maybe the live have ended or haven't start yet?
```
So it only works when the live show has _already started_, but that would be usually too late. Better to do some polling on that. (so `you-get` can record the stream as soon as it is available)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1268)
=> [SHOWROOM] Do polling on offline broadcasts

src/you_get/processor/rtmpdump.py
```
python3 you-get -p mpv http://www.zhanqi.tv/edmunddzhang
Site:       zhanqi.tv
Title:      【老E】正义的直播间
Call rtmpdump:
rtmpdump -r rtmp://dlrtmp.cdn.zhanqi.tv/zqlive//9469_lNZYA?k=14e460f56dd93526eac8f92f0ec3d27a&t=57905434 -o - | mpv -
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
```
So it should be working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1294)
=> [Processor] Fix rtmpdump not portable under Windows

src/you_get/common.py
Some ISPs in mainland China now pollutes DNS for websites like tumblr and youtube. When using SOCKS proxy, we need to resolve the DNS through the SOCKS proxy, too.
This patch will enable resolving DNS through the specified SOCKS proxy, so it would work correctly.
To validate this patch, you can use a SOCKS5 proxy (127.0.0.1:1080 in this case) and then issue the following command:
`you-get -s 127.0.0.1:1080 http://muslimkings.tumblr.com/post/146985235471/me-when-a-straight-white-boy-tries-talking-2-me`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1290)
=> fix DNS resolve issue when using socks proxy

src/you_get/extractors/youku.py
Currently Youku playlist download is buggy, it downloads only the first page. Issue #1033 is opened for this problem.
The cause is that Youku's URL of the playlist page does not match what the script expects, so the script degrades to download only the first page.
This PR will fix the issue by modifying the URL and try to traverse all the pages.
You can try it with:
`you-get http://list.youku.com/albumlist/show?id=22238259&ascending=1&page=1`
and it should download all of the 50 videos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1289)
=> Fix Youku playlist download problem

src/you_get/extractors/bilibili.py
There may be space around the finally file name. 
It's necessary for these who embed `you-get` in their program and get the title from stdout.
Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1309)
=> [bilibili] video title may have space around

src/you_get/extractors/douyutv.py
some channel on event will redirect to event page
exp. http://www.douyu.com/65251 redirect to http://www.douyu.com/cms/zt/RioOlympics.html#a
if channel is on event, use entering url to get room_id, and non-digital room_id will not work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1338)
=> [Douyutv]fix channel on event

src/you_get/extractors/douyutv.py, src/you_get/processor/ffmpeg.py
```
python3 you-get -o dow http://www.douyu.com/611813
Site:       douyu.com
Title:      台妹髮型師～美髮院直播
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://hdla.douyucdn.cn/live/611813re7VjmtaHO.flv?wsAuth=27185bfe7901f7d65f88834a427ef3dd&token=web-0-611813-260fc67c9f304fe923401dc7d0406014&logo=0&expire=0 -c copy -bsf:a aac_adtstoasc dow/台妹髮型師～美髮院直播.flv
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1342)
=> Fix ffmpeg wrong folder format and douyu discard output folder

src/you_get/extractors/bilibili.py
Fix #1371 .
Good to have the old times back.
```
$ python3 you-get -di "http://www.bilibili.com/video/av6018455/"
[DEBUG] get_content: http://www.bilibili.com/video/av6018455/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=9769941&from=miniplay&player=1&sign=2983bd7ac2a79330b3c5012f86dc5c26
Site:       bilibili.com
Title:      其实我喜欢你 但是···对不起 最后我放弃了
Size:       68.8 MiB (72146927 Bytes)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1376)
=> [Bilibili] Change back to extract via interface API with Miniloader's key

src/you_get/common.py, src/you_get/extractor.py, src/you_get/extractors/iqiyi.py, src/you_get/extractors/netease.py, src/you_get/processor/ffmpeg.py
[universal] fix issue: "flush" is not available in Python under 3.3
Changes:
1. added a new function in common module named "print_more_compatible", which supports 'flush' keyword in pyver < 3.3 (e.g. 3.2.x), so the program won't be stopped by the unexpected exception. And in pyver >=3.3, it is identical as the built-in print function.
2. added "import" command in related files to overload the print function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1390)
=> [universal] fix issue: "flush" is not available in Python under 3.3

src/you_get/extractors/panda.py
Added support for panda.tv streams that do not use the standard plflag, it is mostly mobile streams that use the nonstandard plflags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1393)
=> Added support for panda.tv streams that do not use the standard plflag

src/you_get/util/fs.py
translate char | to - in filename at all platform, for ffmpeg use char | to concat video slices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1448)
=> translate char | to - in filename for ffmpeg concat

src/you_get/common.py, src/you_get/extractors/baidu.py
Can download Baidu Cloud shares.
What works in this fix:
- Can download single file (w/ or w/o password) from Baidu Cloud Disk sharing
Known limitations:
- Can't bypass CAPTCHAs
- Cookies with login information is needed when downloading videos and some special :tm: files.
- Can't batch download a folder of files (will trigger errors)
Sorry for getting this so late and somewhat incomplete, I apologize
I remembered some issues relating to this, but I can't remember now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1461)
=> Fix Baidu Cloud support

src/you_get/extractors/dailymotion.py, src/you_get/processor/ffmpeg.py
1. Fix a bug in `ffmpeg_download_stream()`  (`params` was not actually passed to `ffmpeg`).
2. Switch the Dailymotion downloader to `download_url_ffmpeg`.
3. Add support for 1080P.
N.B. There seems to be a bug in FFmpeg that it doesn't handle URLs with fragment identifier `#` well. Both curl and wget truncate all characters starting from `#`, but ffmpeg includes it anyway, which invalidates the request and errs with 403.
```
GET /sec(565fe991420338c2d12acdfbe9ca64d3)/video/121/388/134883121_mp4_h264_aac_hd_2.m3u8#cell=core HTTP/1.1
Accept: */*
Range: bytes=0-
Connection: close
Host: proxy-069.dc3.dailymotion.com
Icy-MetaData: 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fix Dailymotion

README.md, src/you_get/extractors/huomaotv.py
HuomaoTV's mobile website takes a new url format.
Also added a row to the table of support list in README.
```
you-get -p mpv http://www.huomao.com/44
Site:       huomao.com
Title:      Faceless vs SG.T_火猫直播_年轻人的直播社区
Type:       Unknown type (m3u8)
Playing: http://live-ws.huomaotv.cn/live/35ftHT/playlist.m3u8
(+) Video --vid=1 (h264)
(+) Audio --aid=1 (aac)
AO: [coreaudio] 44100Hz stereo 2ch floatp
VO: [opengl] 1920x1080 yuv420p
AV: 00:00:02 A-V:  0.000 Cache:  2s+0KB
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1480)
=> Fix(huomao): adapt to new url format

src/you_get/common.py, src/you_get/extractors/__init__.py, src/you_get/extractors/icourses.py
Add support for iCourses
Should close #1451
**Known issues**
- Playlist download **ONLY** can originate from `http://www.icourses.cn/coursestatic/course_*.html` like sites
- Sometimes, the server will refuse the request due to high traffic (rush hour?)
- Sometimes, the request will fail due to poor network condition (but will retry)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1472)
=> icourse: add supprt

src/you_get/extractors/embed.py
Hyphen-minus (`-`) is a valid character in Tudou's video ID. It's even present in the second pattern of `tudou_embed_patterns`, just not the first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1492)
=> [embed] correct tudou pattern

src/you_get/processor/ffmpeg.py
Add `'-bsf:a', 'aac_adtstoasc'` params to ffmpeg, solves #1458 . I have manually tested this with some other video sites which use `ffmpeg_concat_flv_to_mp4()` and it seems everything works fine, the bsf param have no side effect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1518)
=> [mgtv] add bsf:a aac_adtstoasc to ffmpeg params, fix #1458.

src/you_get/extractors/youtube.py
The MPEG-DASH MPD does not always contain the `yt:contentLength` field, and that causes failures in extracting 1080P streams, e.g.,
- https://www.youtube.com/watch?v=5YTCY7wm0Nw
- https://www.youtube.com/watch?v=SUMc73R9f5o
This PR does not, however, fix signature-related issues, as in #1109:
- https://www.youtube.com/watch?v=29mSe-5raVQ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1527)
=> [YouTube] Fix DASH MPD for some streams (1080P)

src/you_get/common.py, src/you_get/extractors/youtube.py
Requires `ffmpeg`.
```
$ you-get -di 'https://www.youtube.com/watch?v=RX8nEGQ1DeY'  
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=RX8nEGQ1DeY
site:                YouTube
title:               CNN Live News Donald Trump Thank you Rally 12-1-16 CNN Donald Trump Carrier speech CNN News Stream
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1541)
=> [YouTube] Add support for Live, fix #37

src/you_get/extractors/lizhi.py
Lizhi extractor has stopped working. In particular, there are two major changes:
- URL format change: no more `#/` in URL paths (http://www.lizhi.fm/#/1309873/ => http://www.lizhi.fm/1309873/);
- The `/api/audio/{radio_id}/{audio_id}` API now returns 404.
This is a rewrite based solely on the `/api/radio_audios` API, which was previously only used in playlist extraction. Since I could not locate a `/api/audio/{radio_id}/{audio_id}` replacement (I only checked some XHR requests in the web interface), for single episode downloads, I'm simply looking up the ID among the full list of episodes. If someone knows an endpoint comparable to `/api/audio/{radio_id}/{audio_id}` I'm all ears.
To test this new extractor, you can try the sample URLs in the source code:
```sh
$ you-get …
```
=> [lizhi] extractor overhaul

src/you_get/extractors/embed.py
Sample embed: for http://www.bilibili.com/video/av5079467/:
```html
<embed height="415" width="544" quality="high" allowfullscreen="true" type="application/x-shockwave-flash" src="http://static.hdslb.com/miniloader.swf" flashvars="aid=5079467&page=1" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash"></embed>
```
(See the "分享" button on the video page.)
Sample usage after this patch:
```
$ you-get --debug https://goo.gl/jSPH9A
[DEBUG] get_content: https://cdn.rawgit.com/zmwangx/7971f208bdb7ebc1bfc44e504789854f/raw/b133e9a07018d894b00e2490022ab078cfa04360/bilibili-embed.html
[DEBUG] get_content: http://www.bilibili.com/video/av5079467/
[DEBUG] get_content: http://interface.bilibili.com/playurl?&cid=8277792&from=miniplay&player=1&sign=df282f440d …
```
=> [embed] add support for bilibili's embedded player

src/you_get/processor/ffmpeg.py
Relative paths in the concat list are considered relative to the parent directory of the script, not the calling directory. This isn't entirely obvious from the documentation, but it is easy to infer from the concat demuxer's concept of "safety", and easy to test (confirmed on FFmpeg 3.2.2). See https://ffmpeg.org/ffmpeg-all.html#concat-1 for details.
This commit fixes the wrong relative paths when `--output-dir` is specified and not pwd.
This commit also
- Factors out common concat list writer code;
- Slightly simplifies the code to collect FFmpeg params (on Py35+ we can further simplify by unpacking `LOGLEVEL` with the star operator right in the list literal).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> [ffmpeg] fix concat list when output dir is not pwd

src/you_get/processor/ffmpeg.py
Occasionally, the FFmpeg invocation fails (which could be due to bugs in you-get; see #1558 for instance), but `-loglevel quiet` means nothing is printed other than the exit status (pretty much always 1) in Python's traceback, which is not helpful at all.
This commit restores FFmpeg's regular output (`-loglevel info`) when `--debug` is specified. We're not using `verbose`, `debug` or `trace` because those levels are mostly only useful for debugging FFmpeg itself, which is not our goal.
Due to lack of meaningful API to access the global logging level, this is a hack based on two assumptions:
1. When `--debug` is enabled, the root logger level is set to `DEBUG`;
2. `processor.ffmpeg` is lazily imported, after command line options are parsed.
---
This change is [<img …
=> ffmpeg: set loglevel to info in debug mode

src/you_get/extractors/qq.py
下载微信文章里的视频。其实更好的解决办法是 #1281，但是微信域名的 URL 会被分派到这边，所以就这样了。
example url:
http://mp.weixin.qq.com/s?__biz=MzA3OTgxODI4NQ==&mid=2653200488&idx=1&sn=bd6d0279b2430cc208d9da74226871db&chksm=847dbb2ab30a323c4b1735887158daf1e295abe586aff0a646ce4257a48010f80bcfb1379c95&scene=0#rd
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1607)
=> [qq] support for videos embedded in weixin

src/you_get/extractors/bilibili.py
The older code of title naming results in useless and repetitive file naming under certain circumstances like "1.Part1.flv" for multi-part videos
This one-line patch fixed the issue by appending video title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1571)
=> [BiliBili] Better Multi-Part Video Naming

src/you_get/extractors/youku.py
When I want to download youku video from youku.com using my python code instead of command line, I found that it raise one exception. Like this:
```
>>> youku.download('http://v.youku.com/v_show/id_XMjE4Nzg2NzM3Ng==.html', info_only=False, output_dir='.', merge=True)
File "<stdin>", line 1, in <module>
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractor.py", line 41, in download_by_url
self.prepare(**kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/you_get/extractors/youku.py", line 147, in prepare
request._opener.add_handler(handler)
AttributeError: 'NoneType' object has no attribute 'add_handler'
```
Then I check the code, and I found the `request._opener` is …
=> fix youku.py bug

src/you_get/extractors/youtube.py
Today when I try to download youtube video, I got an error like below.
```
$ ./you-get -d http://www.youtube.com/watch\?v\=pzKerr0JIPA
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=pzKerr0JIPA
[DEBUG] get_content: https://www.youtube.com/watch?v=pzKerr0JIPA
[DEBUG] get_content: https:/yts/jsbin/player-ko_KR-vflSzkno7/base.js
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['http://www.youtube.com/watch?v=pzKerr0JIPA']
File "/Users/leap/you-get/src/you_get/extractors/youtube.py", line 263, in prepare
dashmpd = ytplayer_config['args']['dashmpd']
KeyError: 'dashmpd'
During handling of the above exception, another exception occurred:
File "./you-get", line 11, in <module> …
```
=> Fix youtube extractor bug

src/you_get/extractors/youtube.py
YouTube keeps updating the `base.js`. That's it.
https://www.youtube.com/yts/jsbin/player-da_DK-vflWlK-zq/base.js
```
$ yg -di 'https://www.youtube.com/watch?v=raNaAVxHqK8'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=raNaAVxHqK8
[DEBUG] get_content: https://www.youtube.com/watch?v=raNaAVxHqK8
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-da_DK-vflWlK-zq/base.js
you-get: version 0.4.648, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=raNaAVxHqK8']
File "/home/soimort/.local/lib/python3.6/site-packages/you_get/extractors/youtube.py", line 263, in prepare
dashmpd = ytplayer_config['args']['dashmpd']
KeyError: 'dashmpd'
During handling of the above exception, another exception …
```
=> [YouTube] Fix signature extraction

src/you_get/common.py
This is a follow-up to #999.
This commit adds the
<function_name>: <url>
debug message, which was previously only emitted by `get_content` and `post_content`, to all high level utility functions with network requests except `url_size`, `url_save` and `url_save_chunked` (in order not to ruin progress bars).
---
Rationale: I've been very happy with the `get_content: <url>` messages since their introduction, so expansion to all utility functions seems a good idea to me.
To respond to the original review comment in #999:
> Honestly speaking, I've not needed debug messages like this; leaving tcpdump open and you'll get a bit of everything underhood (at least for HTTP-only sites like Youku and Tudou, which is commonly the case for most Chinese websites).
>
> However, it could be easier to tell …
=> [common] log URLs in more functions with network requests

src/you_get/extractor.py
fix https://github.com/soimort/you-get/issues/1703
test case
```
./you-get -i 'http://www.iqiyi.com/v_19rradj4jc.html'
```
```
site:                爱奇艺 (Iqiyi)
title:               实拍一男子漂移竟将自己甩出车外 险遭碾压
- format:        TD
container:     m3u8
video-profile: 720p
- format:        HD
container:     m3u8
video-profile: 540p
- format:        SD
container:     m3u8
video-profile: 360p
- format:        LD
container:     m3u8
video-profile: 210p
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1705)
=> do not print size when container is m3u8

src/you_get/common.py
When you pass a non-ascii url to you-get, for example, url with Chinese character, get_response(url) will throw a UnicodeEncodeError, causing you-get to terminate with an error message asking you to set locale to UTF-8. But setting locale to UTF-8 won't fix the problem, since it is a URL encoding problem.
This problem is rare, since browsers will encode the url when you copy it out, thus the url you copy from browsers and pass to you-get will always be encoded in URL-conformed format. However, if you use a script to scrape a web page and then pass the urls you find in the page directly to you-get, you will get this error.
This patch addresses this issue by encoding the url passed to get_response(). It should not affect normal URLs, and should allow users to pass non-ascii URLs directly to …
=> fix non-ascii url

src/you_get/extractors/mgtv.py
fix #1760
test case:
```
./you-get -i 'http://www.mgtv.com/hz/bdpz/308921/3861140.html?cxid=19sgybcmgy'
site:                芒果 (MGTV)
title:               歌手第8期：张杰忘我演唱现场泪崩痛哭 迪玛希抱恙出征致敬韩红
- format:        hd
container:     ts
video-profile: 超清
size:          1036.0 MiB (1086294832 bytes)
- format:        sd
container:     ts
video-profile: 高清
size:          575.4 MiB (603316252 bytes)
- format:        ld
container:     ts
video-profile: 标清
size:          283.6 MiB (297358284 bytes)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1761)
=> [mgtv] add url patterns

src/you_get/extractors/xiami.py
继 #1650 之后，又遇到了新的不能解析的 URL： http://www.xiami.com/song/xL4jJGd3829
现在应该都能解析了。顺手修了歌曲名不对的问题。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1756)
=> [xiami] 继续修非数字 URL

src/you_get/extractors/miaopai.py
`url = match1(a, r'<video id=.*?src=[\'"](.*?)[\'"]\W')`
这条规则weibo可能会变动，如果下载不了，80%是它的原因
`download_urls([url], title.replace('\n',''), ext, total_size=None, output_dir=output_dir, merge=merge)`
文件名会包含回车，所以删除它。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1775)
=> make video.weibo.com downloadable

src/you_get/util/log.py
`xterm-color`, `xterm-16color`, `xterm-88color` and `xterm-256color` are now covered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/soimort/you-get/1745)
=> log: mark xterm* terminals as ANSI escape sequences-compatible

src/you_get/common.py
#1836
```
./you-get  -O foo 'http://v.youku.com/v_show/id_XMjY5MTQ1MDg2OA==.html'
site:                优酷 (Youku)
title:               朴槿惠今天在看守所接受二次讯问 170406
stream:
- format:        mp4
video-profile: 高清
size:          9.6 MiB (10041856 bytes)
Downloading foo.mp4 ...
```
=> common.py append ext name when -O flag existed

src/you_get/extractors/youku.py
This is especially helpful in cases where the entire video is blocked by paywall, resulting in an unhelpful error message
```
you-get: [Failed] Cannot extract video source.
```
I spent quite a few minutes debugging a URL like that,^ which could have been saved by the message
```
you-get: Skipping 27 out of 27 segments due to paywall
```
added by this commit.
^The video is completely region-blocked where I am, so I didn't know it was behind a paywall before feeding it to you-get — with a Mainland-based extractor proxy of course. That should explain my initial confusion — it would have been obvious if I checked its availability in a Unblock Youku-enabled browser session first. Still, more self-contained information should make you-get better.
---
This change is [<img …
=> youku: warn about segments skipped due to paywall

src/you_get/common.py, src/you_get/processor/ffmpeg.py
1. print stack trace when ```UnicodeEncodeError``` caught
2. remove deugging message from ```get_html``` and ```get_decoded_html```, which call ```get_responce``` and print two message for one HTTP request.
3. print a hit when an ffmpeg nightly build, which uses concat protocol when merges video segs.
=> Tuning debugging message

src/you_get/common.py, src/you_get/extractors/bilibili.py
1. Add `Referer` in both `url_info()` and `download_urls()`.
2. Specify the `Range` explicitly. 
Test links:
* http://www.bilibili.com/video/av10289657/
* http://www.bilibili.com/av10299156
* http://www.bilibili.com/av10354175
=> Fix Bilibili 403 error

src/you_get/common.py
#1942
details are in the following discussion.
=> [common] url_info should not ignore refer when called in url_save

src/you_get/extractors/ximalaya.py
Now ximalaya api server checks UA. If there's 'python' (case insensitive) in UA it will return empty content instead of json string.
```
curl 'http://www.ximalaya.com/tracks/330957273.json' -H 'user-agent: python-urllib/3.5'
```
return nothing
```
curl 'http://www.ximalaya.com/tracks/3.json' -H 'user-agent: ython-urllib/3.5'
{"res":false}
```
```
./you-get -d 'http://www.ximalaya.com/2982325/sound/30957273'
[DEBUG] get_content: http://www.ximalaya.com/tracks/30957273.json
[DEBUG] ximalaya_download_by_id: http://audio.xmcdn.com/group24/M04/9E/A9/wKgJMFiq4_iDnkMKAZ_V_DLoKG4117.m4a
Site:        ximalaya.com
title:       01游玩天桥
Type:        MPEG-4 audio m4a
Size:        N/A
Downloading 01游玩天桥.m4a ...
100% ( 26.0/ 26.0MB) ├█████████████████████████████████████████┤[1/1]    2 MB/s
```
=> [Ximalaya] fix #1955

src/you_get/extractors/ku6.py
Fix error when parse url http://v.ku6.com/show/dBKZbnO51PWi7N2xRa3Bmw...html
Case the sub-url end with mp4?AccessKeyId=...&Expires=...&Signature=...
So the regex in ku6 should be improved to fix the error.
=> [ku6] Fix error when parse url's extension

src/you_get/extractors/miaopai.py
1. for ```miaopai_download```
get fid from the urls and raise exception if no pattern can be matched with
2. change ```miaopai_download_by_url``` to ```miaopai_download_by_fid```
access the mobile page only once and fetch both the video url and title
test case for /p/230444
```
./you-get 'http://weibo.com/p/230444bf778220fe93887030056812aeaffa39'
Site:       miaopai
Title:      #邓紫棋# "十支歌选一首""不能选 十只手指有长短"[喵喵]"如果给这张专辑打分""一百分！！"这傲娇的小公举😂😂😂
Size:       0.94 MiB (988586 Bytes)
Downloading #邓紫棋# "十支歌选一首""不能选 十只手指有长短"[喵喵]"如果给这张专辑打分""一百分！！"这傲娇的小公举😂😂😂.mp4 ...
100% (  0.9/  0.9MB) ├█████████████████████████████████████████┤[1/1]  296 MB/s
```
test case for ```fid=\d{4}:\w{32}```
```
./you-get 'http://weibo.com/tv/v/d052ec5abf86de2354f8ac21f1defe88?fid=1034:d052ec …
```
=> refactoring miaopai.py

src/you_get/extractor.py, src/you_get/extractors/bilibili.py
~~在common.py里加了get_content_and_redirected这样一个函数，以tuple返回content和redirected_url~~
1. 用url_locations处理redirects，修正了#1693
test case
```
./you-get -i 'http://www.bilibili.com/video/av7873772/'
Site:       bilibili.com
Title:      URARA迷路帖 [1 少女与占卜、偶尔的露肚皮]
Size:       345.69 MiB (362486000 Bytes)
```
2. 正确处理bangumi的episode titles
test case
```
./you-get -i 'http://bangumi.bilibili.com/anime/835/play#15014' 'http://bangumi.bilibili.com/anime/3462/play#89073' 'http://bangumi.bilibili.com/anime/1660/play'
Site:       bilibili.com
Title:      我们仍未知道那天所看见的花的名字。 [1 超和平busters]
Size:       176.81 MiB (185402909 Bytes)
Site:       bilibili.com
Title:      双星之阴阳师 [17 师傅赋予的红色证明]
Size: …
```
=> bilibili multi fixes

src/you_get/extractors/youtube.py
just add a forward declaration of local variable `ytplayer_config` in Youtube.prepare method since the variable is invisiable to the expression in line 202.
=> fix 'reference before declaration' error in youtube extractor

src/you_get/extractors/tudou.py, src/you_get/extractors/youku.py
NOTE:
1.  ```yxon``` not impled. F. I. 10 segs in hd3, 8 ones in hd2, 5 ones both in mp4 and flv. 28 extra network requests will be sent, which makes the program seem stuck or produces lots of noise in the debugging log. #1058
2.  Failed with ```http://v.youku.com/v_show/id_XMjc3MjQ0MjEwMA==.html```. ep40 of Zetianji. But it works when downloading ep1 and ep45. Perhaps you should curse the CDN before a VIP user of youku find out what's wrong.
---
1. ```yxon```没有放进代码里。比如一个视频，hd3有10个片段，hd2有8个，mp4和flv各5个，那么一共需要发出28个网络请求，程序会看上去像卡住了一样，或者输出大量没什么用的debugging log。另外可以参考 #1058 ，有人需要。
2. 择天记第40集下载会失败（hd3，其他分辨率正常）。但是择天记的第一集或是第45集都正常，选1080p需要vip所以也没法在浏览器里面看是不是正常。大概只能怪youku的CDN了。
```
$ ./you-get -d 'http://v.youku.com/v_show/id_XMjc4MTQ3MzY5Mg==.html' …
```
=> [youku]update api

src/you_get/extractors/youtube.py
Due to a recent API change. (fixes #2123)
```
$ ./you-get -d https://www.youtube.com/watch\?v\=jNQXAC9IVRw
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=jNQXAC9IVRw
[DEBUG] get_content: https://www.youtube.com/watch?v=jNQXAC9IVRw
[DEBUG] get_content: https://www.youtube.com/api/timedtext?caps=&expire=1499495617&sparams=caps%2Cv%2Cexpire&v=jNQXAC9IVRw&hl=da_DK&key=yttt1&signature=A416DB1E3B22356F2C4B5A471412143C498AD8A0.5316EB548FB6F5A05C856A0C4DB8F8FE43392BCE&lang=en
[DEBUG] get_content: https://www.youtube.com/yts/jsbin/player-vfl2U8fxZ/da_DK/base.js
site:                YouTube
title:               Me at the zoo
stream:
- itag:          43
container:     webm
quality:       medium
size:          0.5 MiB (564215 bytes)
Downloading Me at the zoo.webm ...
100% ( …
```
=> [YouTube] Fix caption tracks

src/you_get/extractors/flickr.py
ground-up refactor for flickr extractor.
- now based on flickr offical api methods.
- add full support for photo collection(photostream/album/favorite/gallery/group-pool/) batch downloading.
- enable specificing maximum resolution level by using --itag=[okhlczmnstq(sq)] argument, works for photo collections only.
Note that this extractor is mostly based on flickr api, the only information extracted from url or page are UIDs, so we don't need to test pages with variant appearance. For example, no matter how many pages an album used to list all its photos, we could simply get the full photo list by calling 'flickr.photosets.getPhotos'. So the url below just try to cover all the supported entries only, and it's better to :%s/per_page=500/per_page=5/g before testing, since it's hard to see a …
=> rebuild flickr extractor

src/you_get/extractors/iqiyi.py
#1894
test cases:
```
./you-get -i 'http://www.iqiyi.com/v_19rr9y7d7s.html?vfm=m_103_txsp#curid=625521800_eb5dcb7fbd6399a6ef85a45386f51e3b'
site:                爱奇艺 (Iqiyi)
title:               魔力美食_20170228期
- format:        TD
container:     m3u8
video-profile: 720p
- format:        HD
container:     m3u8
video-profile: 540p
- format:        SD
container:     m3u8
video-profile: 360p
- format:        LD
container:     m3u8
video-profile: 210p
```
```
./you-get -id 'http://www.iqiyi.com/v_19rr9y7d7s.html?vfm=m_103_txsp#curid=598026100_0bf7ea3bed1c77c42590927fba73d3d8'
[DEBUG] get_response: http://www.iqiyi.com/v_19rr9y7d7s.html?vfm=m_103_txsp#curid=598026100_0bf7ea3bed1c77c42590927fba73d3d8 …
```
=> fix iqiyi tiltes when accessed with curid=

src/you_get/extractors/bilibili.py
Some episode indices are not purely numbers, causing `ValueError` during converting index from string to float.  For example, some indices are like `1-2` or `20+21` in [http://bangumi.bilibili.com/anime/5707](http://bangumi.bilibili.com/anime/5707).
The following is an error example from the current version.
```
[Movies] $> you-get --debug "http://bangumi.bilibili.com/anime/5707/play#113765"
[DEBUG] url_locations: http://bangumi.bilibili.com/anime/5707/play#113765
[DEBUG] get_content: http://bangumi.bilibili.com/anime/5707/play#113765
[DEBUG] get_content: http://bangumi.bilibili.com/jsonp/seasoninfo/5707.ver?callback=seasonListCallback&jsonp=jsonp&_=1501492179929
you-get: version 0.4.803, a tiny downloader that scrapes the web.
you-get: …
```
=> Fix parsing irregular episode index

src/you_get/extractors/instagram.py
Fix Instagram downloader always downloading to current directory, ignoring `-o` option.
#2188
=> [instagram] Fix always downloading to current dir, ignoring `-o`

src/you_get/common.py, src/you_get/extractors/zhanqi.py
```
$ ./you-get -d 'https://www.zhanqi.tv/edmunddzhang'
[DEBUG] get_content: https://www.zhanqi.tv/api/static/v2.1/room/domain/edmunddzhang.json
Site:       www.zhanqi.tv
Title:      EdmundDZhang: 【老E】今晚可能休息？！
Type:       M3U8 Master m3u8
M3U8 Url:   http://dlhls.cdn.zhanqi.tv/zqlive/9469_lNZYA.m3u8
Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://dlhls.cdn.zhanqi.tv/zqlive/9469_lNZYA.m3u8 -c copy -bsf:a aac_adtstoasc EdmundDZhang- 【老E】今晚可能休息？！.mp4
ffmpeg version 3.3.1 Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 8.1.0 (clang-802.0.42)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang …
```
=> [common zhanqi]m3u8 code in common; rewrite zhanqi

src/you_get/common.py
Recently I started to get timeout in response.read(), this commit will make it retry automatically if timeout.
=> [common] retry if response.read() timeout

src/you_get/common.py
see also https://github.com/soimort/you-get/issues/1181.
功能上应该完全没有改变，输出上，呃，它变长了……好处是选项的定义更加声明化，不会忘记改帮助信息了的。也添加了几个互斥组。
需要的话，我可以进一步优化。
=> use argparse instead of getopt

src/you_get/common.py
I've also run pylint so there should not be more obvious errors like this one.
fixes #2351
=> fix load_cookies local name error

src/you_get/common.py, src/you_get/extractors/giphy.py
[Giphy.com](https://giphy.com) converts gifs into some formats, `mp4` is one of them.
`you-get https://giphy.com/gifs/MTVU-relax-chill-26n6UOQke3xCpsbWo`
Will download: [https://media.giphy.com/media/26n6UOQke3xCpsbWo/giphy.mp4](https://media.giphy.com/media/26n6UOQke3xCpsbWo/giphy.mp4)
I hope it's all ok for merge. Let me know if it needs changes. :)
=> new extractor: giphy.com

src/you_get/common.py
当三次重试都失败时，该函数实际会返回None，而不是抛出最后一个异常，导致流程异常进行下去，最终造成NoneType系列的异常，而不是真实的网络异常
=> fix urlopen_with_retry may return None

src/you_get/extractors/bilibili.py
现在这个逻辑，在结合`-l`获取某个list的时候，list的title会变成None，因为已有的正则匹配失败了。
翻了下B站的前端，新增了一个meta标签，里面有视频列表的title，因此在原有正则获取不到title的情况下，再从meta标签尝试获取一次
=> 改进B站获取title的逻辑

src/you_get/extractors/yixia.py
Miaopai is using https now. Fix url pattern when download miaopai videos
```
./you-get -di "https://www.miaopai.com/show/i8xTI~lQ~M1z0oXazPj0Zi0cLvoov~HBYf1A~Q__.htm"
you-get: version 0.4.939, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.miaopai.com/show/i8xTI~lQ~M1z0oXazPj0Zi0cLvoov~HBYf1A~Q__.htm'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=True, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
File "./you-get", line 11, in <module> …
```
=> Fix miaopai download failed

src/you_get/common.py
现在的进度条显示，在windows下会因为多算了一个字符的宽度，导致\r不生效，仍然出现换行显示的行为，多减去一个字符即可修复
=> fix bar display under windows terminal

src/you_get/extractors/qq.py, src/you_get/extractors/sohu.py
Sohu's url changed from http://tv.sohu.com/ to https://tv.sohu.com/.
Some urls like https://tv.sohu.com/20171108/n600244028.shtml
https://tv.sohu.com/20171107/n600243808.shtml
https://tv.sohu.com/20171108/n600244032.shtml  can't download.
qq: 
http://v.qq.com/cover/p/ps6mnfqyrfo7es3.html?vid=q0181hpdvo5 -> https://v.qq.com/x/cover/ps6mnfqyrfo7es3/q0181hpdvo5.html?
=> [sohu]add https

src/you_get/extractors/mgtv.py
Mgtv extractor failed with `https` link, this pull request has fix the problem. Now it works on my mac both `http` and `https` links.
=> Update the regex for mgtv extractor, adapt to https

src/you_get/extractors/vine.py
Now if no description in video file metadata found then user name and
video id will be used
=> [vine] fix empty file name if no description found

src/you_get/extractors/bilibili.py, tests/test.py
bilibili got a weird page([https://www.bilibili.com/video/av16907446/](https://www.bilibili.com/video/av16907446/)), there is no `=` between the `title` property and it's value.
So I changed the regular expression, now it directly matches the contents of the `h1`.
I also updated the unit test.
=> [bilibili] fix title regex

README.md, src/you_get/common.py, src/you_get/extractors/__init__.py, src/you_get/extractors/douyin.py, tests/test.py
Add support for [抖音](https://www.douyin.com/)
```console
$ you-get https://www.douyin.com/share/video/6492273288897629454
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
Site:       douyin.com
Title:      请欣赏关了美颜的我🙂
Size:       3.14 MiB (3294451 Bytes)
Downloading 请欣赏关了美颜的我🙂.mp4 ...
100% (  3.1/  3.1MB) ├████████████████████████████████████████┤[1/1]    3 MB/s
```
=> [douyin] add support

src/you_get/extractors/bilibili.py
Add referer header to fix http error code 403,
and user agent to fix http error code 466.
=> fix http code 403 and 466 error for bilibili

src/you_get/extractors/qq.py
发现微信文章的最新的 url 已经改成了类似下面的 url
```
https://mp.weixin.qq.com/s/plb8cvwiSfN7Ejo4H_HHUg
```
原来的代码无法正常工作，这个 pull request 可以解决这个问题。
=> [qq] fix weixin embedded video support

src/you_get/common.py
This is just a suggestion.
Certain sites (known example: tudou.com; other sites may be affected too, currently or in the future) deny access to video URLs unless user agent matches the one used when retrieving URLs from the API, effectively rendering the URLs useless without the proper user agent. Therefore, exposing the user agent (which may not be even to find for casual users) in `-u, --url` output could come in handy at times.
This commit does not affect `--json` output.
Sample sessions:
```
$ you-get -u http://www.tudou.com/programs/view/QjZZ5dzxR9s/
Site:       Tudou.com
Title:      中华人民共和国国歌（义勇军进行曲）
Size:       0.64 MiB (672037 Bytes)
User Agent: Python-urllib/3.6
Real URLs:
http://58.205.218.5/mp4/61/125003061.h264_1.mp4?key=a0cbde8160cf77affa23 …
```
=> [common] print user agent when dumping URLs (-u, --url)

src/you_get/extractors/douyutv.py
#you-get -du https://www.douyu.com/lpl
[DEBUG] get_content: https://m.douyu.com/lpl
...
...
File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1574, in any_download
m.download(url, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/you_get/extractors/douyutv.py", line 81, in douyutv_download
download_url_ffmpeg(real_url, title, 'flv', None, output_dir = output_dir, merge = merge)
File "/usr/local/lib/python3.5/dist-packages/you_get/common.py", line 1013, in download_url_ffmpeg
if params.get('-y', False):  # None or unset ->False
AttributeError: 'NoneType' object has no attribute 'get'
=> Parameter type error

src/you_get/extractors/youku.py
`mp4hd3` format of some videos cannot be extracted with 0513, but can be extracted with 0507.
For example, http://v.youku.com/v_show/id_XMzM2NTk2NTM5Ng==.html, `mp4hd2` is the best format if 0513 is used, however, `mp4hd3` is available if 0507 is used.
=> Change Youku ccode to 0507

src/you_get/common.py
I've noticed that if I download two videos with same names from youtube (e.g. https://www.youtube.com/watch?v=606hmlA_nxw and https://www.youtube.com/watch?v=CLrXTnggUeY), 
only one of them will be saved (usually the bigger one according to the original script `os.path.getsize(output_filepath) >= total_size * 0.9`). However, I want them both while preserving their names from youtube. It looks like there are a lot of changes, but I just added an indent and everything changed.
Also, I've noticed that "force" is not working at all. I fixed that issue.
I'm quite new to coding... Any feedback is appreciated!
not working -f (old version):
fixed -f : (-a does not matter here)
without this new option:
with this new option:
=> Added an auto rename option and fixed the force option

src/you_get/extractors/bilibili.py
the interface  of bilibili interface has changed 
https://www.bilibili.com/video/av20349144/
"https://interface.bilibili.com/v2/playurl?cid=33250486&appkey=84956560bc028eb7&otype=json&type=&quality=0&qn=0&sign=a1b0401c8bf70d676bab133fa032469f"
=> fix bilibili download fail

src/you_get/extractors/youtube.py
#2167 
the reason for UnboundLocalError for dash_webm_a_url is there could be no audio track with ```audio/webm```
```
video/webm;+codecs="vp9"
video/mp4;+codecs="avc1.640032"
video/webm;+codecs="vp9"
video/mp4;+codecs="avc1.640028"
video/webm;+codecs="vp9"
video/mp4;+codecs="avc1.4d401f"
video/webm;+codecs="vp9"
video/mp4;+codecs="avc1.4d401e"
video/webm;+codecs="vp9"
video/mp4;+codecs="avc1.4d401e"
video/webm;+codecs="vp9"
video/mp4;+codecs="avc1.4d4015"
video/webm;+codecs="vp9"
video/mp4;+codecs="avc1.4d400c"
video/webm;+codecs="vp9"
audio/mp4;+codecs="mp4a.40.2"
```
16 tracks, 15 for videos and only one for audio
I believe the correct way is to fetch the ```audio/mp4``` with the ```video/webm``` track
```
./you-get -id https://www.youtube.com/watch\?v\=VaoAU6PvuTg …
```
=> [youtube]use mp4_audio track when no audio track for webm

src/you_get/extractors/youku.py
0507 doesn't seem to honour cookies when they're loaded, whilst 0507 worked just fine.
=> Use 0513 when cookies are used

src/you_get/extractors/ixigua.py
由于ixigua网站规则改变：所有www.ixigua.com的域名将跳转至m.365yg.com或者www.365yg.com,为了避免代码重复，ixigua.py中直接调用了toutiao .py接口
=> 修复ixigua在获取视频信息时403错误

src/you_get/processor/ffmpeg.py
`ffmpeg -version` gives "ffmpeg version 2.8.14-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers" on Ubuntu Xenial, which make int() failed during extracting version code.
=> Move the warning message output to standard error.

src/you_get/extractors/qq.py
=> 腾讯视频默认下载SHD视频

src/you_get/util/fs.py, src/you_get/util/os.py, tests/test_util.py
I am using you-get on Windows Subsystem for Linux. There were so many times that, you-get failed to rename the temp file after download finished. I found they are all related to some special characters in the title, which are reserved in Windows, but not properly handled.
```
[/mnt/d]$ you-get --debug https://www.youtube.com/watch?v=1Ndnmc-R-UM
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=1Ndnmc-R-UM
[DEBUG] get_content: https://www.youtube.com/watch?v=1Ndnmc-R-UM
[DEBUG] get_content: https://www.youtube.com/api/timedtext?sparams=asr_langs%2Ccaps%2Cv%2Cxorp%2Cexpire&xorp=True&caps=asr&v=1Ndnmc-R-UM&hl=en_US&expire=1531701905&key=yttt1&signature=E4A044EABD55346DADD34C8 …
```
=> [util] improve compatibility with WSL

src/you_get/extractors/miaopai.py
fix example: https://weibo.com/tv/v/4263129454962711?fid=1034:4263129454962711
```
> you-get -d --json 'https://weibo.com/tv/v/4263129454962711?fid=1034:4263129454962711'
[DEBUG] get_content: https://weibo.com/tv/v/4263129454962711?fid=1034:4263129454962711
you-get: version 0.4.1099, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://weibo.com/tv/v/4263129454962711?fid=1034:4263129454962711'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=True, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False) …
```
=> [miaopai] support not fixed length fid

src/you_get/common.py, src/you_get/extractors/bilibili.py
Use new API: `https://api.live.bilibili.com/room/v1/Room/playUrl?cid={}&quality=0&platform=web` to get .flv url
And sometimes, response.headers['Content-Type'] is None, fix the `None` to `''`
=> use new bilibili live api, fix None Content-Type

src/you_get/extractors/bilibili.py
old regex can only aim at this:
this PR match the title pattern with html attribute like this
TEST URL:
https://www.bilibili.com/video/av12828695
different title pattern occurs when using `--cookies` to assign the login cookie.
PLZ test the code using `--cookies` to login bilbili and test the 2nd type of title pattern.
=> fix bilibili title regex

src/you_get/extractors/acfun.py
url pattern and html layout of acfun's bangumi page is different from other acfun page , which causes problem
this pr fixs it
~~~
you-get -i http://www.acfun.cn/bangumi/ab5022161
Site:       AcFun.tv
Title:      但是不屈不挠 SAGA (acfun)
Size:       539.6 MiB (565815129 Bytes)
~~~
=> fix acfun bangumi page

src/you_get/extractor.py, src/you_get/extractors/bilibili.py
support 3 types of url:
1. one piece of music
e.g. `https://www.bilibili.com/audio/au639116` 
2. playlist
e.g. `https://www.bilibili.com/audio/am10624?type=2` need --playlist
3. favlist
e.g. `https://www.bilibili.com/audio/mycollection/16803087` need --playlist
have tested on these three types of urls
```
you-get git:(develop) ./you-get https://www.bilibili.com/audio/mycollection/16803087 --playlist
Start downloading music  负面扩张
site:                Bilibili
title:               负面扩张
stream:
- format:        mp4
container:     m4a
size:          3.5 MiB (3648595 bytes)
Downloading 负面扩张.mp4 ...
100% (  3.5/  3.5MB) ├████████████████████████████████████████┤[1/1]  820 kB/s
Start downloading music  谁杀死了知更鸟（小少年·童谣ver）
site:                Bilibili
title:               谁杀死了知更鸟（小少年·童谣ver） …
```
=> [bilibili] support bilibili audio

src/you_get/extractors/bilibili.py
delete useless old regex which sometimes cause error
~~~
you-get --debug  https://www.bilibili.com/bangumi/play/ss25681/?spm_id_from=333.
334.b_62696c695f62616e67756d69.5
......
File "c:\users\fengl\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\bilibili.py", line 267, in bangumi_entry
episode_id = re.search(r'first_ep_id\s*=\s*"(\d+)"', self.page) or re.search(r'\/ep(\d+)', self.url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
~~~
=> fix bilibili bangumi page

src/you_get/extractors/coub.py, src/you_get/processor/ffmpeg.py
Test URL:  https://coub.com/view/19cyub
1) ```params.extend(['-safe', '0'])``` fixes ```[concat @ 0x55b4c8f02980] Unsafe file name 'Test_For_The_Princess!.mp4'```
Before patch: Test_For_The_Princess!_full.mp4 is not created
After patch: Test_For_The_Princess!_full.mp4 created successfully
2) ```round``` fixes ```audio_duration 64.0 + video_duration 8.04 -> 7```
Before patch: video is freezed for last 8 second
After patch: perfect loop
=> fix coub ffmpeg

src/you_get/extractors/pptv.py
Crushed when download from url like `https://v.pptv.com/show/L6xo50i……` :
> you-get: version 0.4.1256, a tiny downloader that scrapes the web.
> you-get: Namespace(URL=['https://v.pptv.com/show/L6xo50i…….html'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
> Traceback (most recent call last):
>   File "d:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "d:\program files\python36\lib\runpy.py", line 85, in …
=> [pptv] support https url

src/you_get/common.py
**Problem:** 
When downloading a youtube video from VPN, it will fail because of ssl error:
`
you-get: Namespace(URL=['https://www.youtube.com/watch?v=JQDHz72OA3c&feature=youtu.be'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, in_secure=False, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
.....
....
self._sslobj.do_handshake()
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: …
=> Support ignore ssl when connecting through vpn by adding option -k

src/you_get/extractors/iqiyi.py
The API `http://mixer.video.iqiyi.com/jp/mixin/videos/` used by the iQiyi extractor to get correct video title seems to have been deprecated and is returning 404 error. For example, for this video `https://www.iqiyi.com/w_19s2jsr8z1.html`, whose `tvid` is `27529587009`, requesting `http://mixer.video.iqiyi.com/jp/mixin/videos/27529587009` returns
```
var tvInfoJs=<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
which is not valid JSON.
This causes the JSON parser to fail and throws an unexpected exception that prevents the download from starting. <https://github.com/soimort/you-get/blob/2e461820f8dbb46bf7aa973e9df02986e758dd10/src/you_get/extractors/iqiyi.py#L141>
Fortunately, the …
=> Fix iQiyi broken api blocking video download

src/you_get/extractors/acfun.py
Correct the title of the file from "早上好 佐贺 早上好 佐贺 (acfun) - 早上好 佐贺" to "佐贺偶像是传奇 早上好 佐贺 (acfun) - 早上好 佐贺".
And also support videos like `http://www.acfun.cn/bangumi/ab5024113_33351_311321`.
=> fix acfun bangumi title

src/you_get/extractors/toutiao.py, tests/test.py
```
[DEBUG] get_response: https://www.365yg.com/i6640053613567675662/#mid=1611922564114440
[DEBUG] get_content: http://i.snssdk.com/video/urls/v/1/toutiao/mp4/None?r=1644525832427347&s=244466975
you-get: version 0.4.1270, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.365yg.com/i6640053613567675662/#mid=1611922564114440'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
File …
```
=> fix toutiao errors

.travis.yml, src/you_get/extractors/baidu.py, src/you_get/extractors/douyutv.py, src/you_get/extractors/panda.py, src/you_get/extractors/zhibo.py
Also:
* Upgrade to Python 3.7 production instead of pre-release
* Upgrade to current Python nightly and 3.8-dev builds
* Remove __sudo__ tag which is now deprecated on Travis CI
[__Python < 3.5 are all end-of-life.__](https://devguide.python.org/devcycle/#end-of-life-branches)  At what point do we drop support for them?
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./src/you_get/extractors/baidu.py:41:20: F632 use ==/!= to compare str, bytes, and int literals
return None if lrc is '' else "http://music.baidu.com%s" % lrc
^
./src/you_get/extractors/zhibo.py:37:8: F632 use ==/!= to compare str, bytes, and int literals
if is_live is not "1":
^
./src/you_get/extractors/douyutv.py:65:8: F632 use ==/!= to compare str, bytes, and int literals
if server_status is …
```
=> Travis CI: Add flake8 test F632 use ==/!= to compare str, bytes, and int literals

src/you_get/extractors/bilibili.py
fix the new type of `高清 1080P+` on bilibili.com
test command:
```bash
you-get --debug -c bilibili.txt --playlist -i "https://www.bilibili.com/video/av40115478"
```
=> add new video type for bilibili.com

src/you_get/common.py
Hi,
Issue and Usage Scenarios:
Due to ffmpeg version and different format of downloaded parts, sometimes the merge of video parts can fail. This will result in 0 bytes merged files. 
When running you-get again, you-get will check the merged file. Although the merged file exists, it's length is 0 bytes and you-get will try to re-download the video parts and re-merge the file. This is for fault tolerance and continues downloading feature, but sometimes, this can be inconvenient.
For example:
I am trying to download 10000+ videos from YouTube. I need to download as many as possible. But the network is not stable and my ffmpeg fails to merge some of the videos. So I run you-get with the 10000+ URLs and get some successfully merged files, some failed merged files and some partially downloaded …
=> add --skip-ignore-size function to skip the file size check

src/you_get/extractors/kugou.py, src/you_get/extractors/le.py
kugou downloading is not working, it shows
you-get -d http://www.kugou.com/song/#hash=529A30C3F0111E54B6D3F900A313E5EF&
album_id=21010416
[DEBUG] get_response: http://www.kugou.com/yy/index.php?r=play/getdata&hash=529A
30C3F0111E54B6D3F900A313E5EF&album_id=None
you-get: version 0.4.1314, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['http://www.kugou.com/song/#hash=529A30C3F0111E54B6D3F90
0A313E5EF'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None,
force=False, format=None, help=False, http_proxy=None, info=False, input_file=No
ne, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_
proxy=False, output_dir='.', output_filename=None, password=None, player=None, p
laylist=False, skip_existing_file_size_check=False, …
=> 酷狗音乐无法正常下载及解决办法

src/you_get/extractors/acfun.py
The original html attributes have changed since the last acfun site's upgrade, it fails to extract the video id and title from the serial `data-xxx` attributes, this pr fixes it by extracting the metadata info from the json data instead.
Please help to review this.
=> Fix the parser issue for acfun videos.

src/you_get/extractors/youtube.py
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=ZTwBlWGHRRE&eurl=https%3A%2F%2Fy
[DEBUG] STATUS: ok
you-get: version 0.4.1314, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.youtube.com/watch?v=ZTwBlWGHRRE'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, skip_existing_file_size_check=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)
File "/Users/mingjun.luo/anaconda3/bin/you-get", line 10, in <module> …
=> Fix bug: unable get video title

src/you_get/extractors/kuaishou.py
快手似乎不把视频url放在meta标签里了, 目前直播视频url存放在网页最后的json中.
解决方法:
1. regex找到当前直播对应的视频url列表
2. 找出最高画质版本对应的url, 这里还处理url中通过utf-8编码的特殊字符
3. 查找第一个title标签找到直播标题
=> 修复快手直播无法下载的问题

README.md, src/you_get/extractors/acfun.py
修复A站番剧下载，之前的方式已经不能用了。顺便改了域名`acfun.tv`→`acfun.cn`。
=> Fix AcFun Bangumi download.

src/you_get/common.py
fix a bug for reading cookies.txt：the UnicodeDecodeError, if cookies.txt include Chinese characters
Example：
cookies.txt include：.v.qq.com       TRUE    /       FALSE   0       ptag    www_baidu_com|movie_v3_new:img:扫毒2天地对决。
The Error：UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 4935: ordinal not in range(128)
=> modify encoding with open cookies file

src/you_get/extractors/ixigua.py
The ixigua downloading fails now:
```
$ you-get "https://www.ixigua.com/i6631065141750268420/\#mid\=63024814422"  --debug
[DEBUG] get_response: https://www.ixigua.com/i6631065141750268420/\#mid\=63024814422
[DEBUG] get_content: https://ib.365yg.com/video/urls/v/1/toutiao/mp4/v02004ad0000bg3477ik781ngjvbjbs0?r=32159770337169047&s=462489322
you-get: version 0.4.1347, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.ixigua.com/i6631065141750268420/\\#mid\\=63024814422'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, …
```
=> [ixigua] Fix error of matching title

.gitignore, src/you_get/extractors/bilibili.py
Support interaction video for bilibili, BFS all possible node and download video. use --playlist option
支持B站的互动视频，使用广度优先搜索所有可能的节点，然后下载对应的视频，使用playlist指令即可
=> [bilibili.py]interaction video support

src/you_get/common.py
- Playing dash_streams is impossible since launch_player is expecting `List[str]`, while VideoExtractor.dash_streams has a type of `List[List[str]]`.  
- This patch should fix that problem and allow dash_streams to be played.
=> Fix playback of VideoExtractor.dash_streams

src/you_get/extractors/naver.py
The recent video on tv.naver was not downloaded, but only the wrong thumbnails were downloaded in the previous code. So I solved this problem by integrating the if-else statement into one.
It also resolved the problem of not being properly stored in the specified output_dir.
* example of wrong result
result of "you-get https://tv.naver.com/v/10984456"
only downloaded thumbnails no video
* can download this video correctly after code change
=> fix extractor naver.py

src/you_get/extractors/sohu.py
针对搜狐号下的视频无法下载的修复
测试链接：https://www.sohu.com/a/365052095_100182082?spm=smpc.author.fd-d.1.1578455373074zxRVlfV
搜狐号下作者不能进行下载的视频列表：https://mp.sohu.com/profile?xpt=OTk4NTg3MDk2MDczNzA3NTIwQHNvaHUuY29t&spm=smpc.vd-land.info.1.1578463489230sivA5hm
=> 修复搜狐号的视频不能下载的问题

src/you_get/extractors/coub.py
Some videos e.g. [https://coub.com/view/286qqx](https://coub.com/view/286qqx) contain `<` characters belonging to tags nested inside
`<script id='coubPageCoubJson' type='text/json'>`.
They get matched early by the regex resulting in an empty variable coub_data.
`Error while downloading files. the JSON object must be str, bytes or bytearray, not NoneType`
Fixed so it matches everything until the closing `</script>` tag.
=> fixed coub_data regex

src/you_get/extractors/netease.py
Some vip download can download through this, others can't. Still looking into it.
example: en-嚣张，jam-不露声色 可下载； yui-again，买辣椒也用券-起风了 下载失败 （格式：歌手-歌名）原来都是VIP才可下载的，怀疑是本来下载后是mp3格式的现在正常工作但如果是ncm格式的不会，我没有网易云会员也不怎么用，所以有没有尊贵的vip可以测试一下上面的四首歌的下载格式分别是什么吗
=> temp fix of netease download

src/you_get/extractors/cntv.py
Since 30/04/2020 the vide URL of 'http://tv.cctv.com/' has change from 'http' to 'https'. when download https type video there will be NotImplementedError raise up. so I filed a PR to update protocal match from 'http' to 'http(s)?' to make it compatiable with 'https' type. 
Sample URLs of 29 and 30:
http://tv.cctv.com/2020/04/29/VIDEEs3t2TeKX57YvCl06Nrp200429.shtml?spm=C31267.PFsKSaKh6QQC.S71105.151
https://tv.cctv.com/2020/04/30/VIDEu06KaGhauLSK21ftxp4G200430.shtml?spm=C31267.PFsKSaKh6QQC.S71105.171
Here is the debug message when download https video:
```error
PS C:\Users\jack\xinwen> you-get --debug https://tv.cctv.com/2020/05/05/VIDEyGh13CUx1HaQb3kFYBUf200505.shtml?spm=C31267.PFsKSaKh6QQC.S71105.2
you-get: version 0.4.1432, a tiny downloader that scrapes the web.
you-get: …
```
=> [CNTV] Support https type downloading from host of tv.cctv.com

src/you_get/common.py, src/you_get/extractors/soundcloud.py, src/you_get/processor/ffmpeg.py, tests/test.py
- 使用静态的 client id, 其过期直接导致 HTTP 401
*解决*: 动态获取 client_id
- can not merge mp3 files
*solution*: using ffmpeg to concat MP3 files
- 支持下载playlist
=> fix: soundcloud: HTTP Error 401: Unauthorized

src/you_get/extractors/ckplayer.py
cElementTree has been deprecated for removal and ElementTree should be used in Python 3. Reference : https://bugs.python.org/issue36543
=> Use ElementTree instead of deprecated cElementTree.

src/you_get/extractors/bilibili.py
For some bangumi on bilibili, only dash formats can be shown when examing formats using `you-get -i`. The expected behaviour I assume should be that both dash and non-dash formats are listed, because that's what happens when a normal bilibili video url is given.
<details>
<summary>Example</summary>
```
~ > you-get -i "https://www.bilibili.com/bangumi/play/ep84340"
you-get: This bangumi currently has 24 videos. (use --playlist to download all videos.)
site:                Bilibili
title:               某科学的超电磁炮：第1话 电击使 Electro Master
[ DASH ] ____________________________________
- format:        dash-flv
quality:       高清 1080P
size:          293.2 MiB (307432119 bytes)
- format:        dash-flv720 …
```
=> Try to show non-dash formats for bangumi videos in bilibili

src/you_get/extractors/iqiyi.py
iqiyi playlist urls changed from `http://www.iqiyi.com` to `//www.iqiyi.com`
extrator is changed to support all 3 kind of link format
1. `http://www.iqiyi.com`
2. `https://www.iqiyi.com`
2. `//www.iqiyi.com`
=> fix iqiyi playlist extrator

src/you_get/extractors/acfun.py, tests/test.py
Should related to #2820 .
I didn't check the download options or all the video types, but this should work.
API `https://www.acfun.cn/rest/pc-direct/play/playInfo/m3u8Auto?videoId=` is not working now(404 NOT FOUND).
```python
[17:16:58] mmmartt:you-get git:(develop) $ you-get -d https://www.acfun.cn/bangumi/aa6002986
[DEBUG] get_content: https://www.acfun.cn/bangumi/aa6002986
you-get: version 0.4.1456, a tiny downloader that scrapes the web.
you-get: Namespace(URL=['https://www.acfun.cn/bangumi/aa6002986'], auto_rename=False, cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, insecure=False, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, …
```
=> fix acfun download fail

src/you_get/extractors/bilibili.py
B站的playurl API加了一个参数 fourk=1 时才会输出4K的播放地址，否则不显示。
bilibili has changed their playurl api, we should add fork=1 to the url params or it will not output the 4k url.
=> [Bilibili] fix bilibili 4k

src/you_get/extractors/xinpianchang.py
之前提取 vid 的 regex 坏了，修一下
测试
```
you-get -i https://www.xinpianchang.com/a10673220
```
```console
site:                xinpianchang
title:               疫情
- format:        1080
quality:       高清 1080P
size:          8.3 MiB (8730005 bytes)
- format:        720
quality:       高清 720P
size:          3.9 MiB (4108878 bytes)
- format:        540
quality:       清晰 540P
size:          2.5 MiB (2634093 bytes)
- format:        360
quality:       流畅 360P
size:          0.5 MiB (537062 bytes)
```
=> [新片场] fix regex to match new vid for Xinpianchang

src/you_get/extractors/netease.py
a fake browser header is required for netease (music.163.com)
or it will return `{"msg":"Cheating","code":-460,"message":"Cheating"}` and write a `{title}.none` file.
=> fix netease song downloading

src/you_get/extractors/youtube.py
yt apparently changed the javascript structure for playlist meta-data.
Without the patch I see this exception:
```
[...]
File "/usr/lib/python3.8/site-packages/you_get/extractors/youtube.py", line 160, in download_playlist_by_url
ytInitialData = json.loads(match1(video_page, r'window\["ytInitialData"\]\s*=\s*(.+);'))
File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```
I added a second regex to account for the new code.
=> [youtube] fix playlist downloads & comprehensive error output

src/you_get/extractors/bilibili.py
for example: 
'count' =130 and 'ps'=100
pc will be 1
in the loop below, you will get wrong video nums: 100, not 130
so, you need a 'math.ceil' not a '//'
=> fix page count error in 'space_video' case

src/you_get/extractors/flickr.py, src/you_get/extractors/mtv81.py, src/you_get/extractors/qingting.py
There are small typos in:
- src/you_get/extractors/flickr.py
- src/you_get/extractors/mtv81.py
- src/you_get/extractors/qingting.py
Fixes:
- Should read `several` rather than `serveral`.
- Should read `channel` rather than `chaanel`.
- Should read `approach` rather than `approch`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

src/you_get/extractors/qq.py
The variable ext must be declared before it can be used.
=> modify qq.py

src/you_get/extractors/bilibili.py
```console
$ ./you-get -i --debug https://www.bilibili.com/video/BV1ex411c7jX
[DEBUG] get_content: https://www.bilibili.com/video/BV1ex411c7jX
[DEBUG] get_content: https://www.bilibili.com/video/BV1ex411c7jX
you-get: version 0.4.1545, a tiny downloader that scrapes the web.
you-get: Namespace(version=False, help=False, info=True, url=False, json=False, no_merge=False, no_caption=False, force=False, skip_existing_file_size_check=False, format=None, output_filename=None, output_dir='.', player=None, cookies=None, timeout=600, debug=True, input_file=None, password=None, playlist=False, first=None, last=None, size=None, auto_rename=False, insecure=False, http_proxy=None, extractor_proxy=None, no_proxy=False, socks_proxy=None, stream=None, itag=None, …
```
=> [bilibili] fix 'NoneType' object is not subscriptable

src/you_get/common.py, src/you_get/extractor.py
Different videos might have the same title. This option `--postfix` postfixes downloaded videos with their unique identifiers to guarantee that they do not get overwritten accidentally.
Currently this option only works for YouTube.
=> Add new option "--postfix" to postfix downloaded files

src/you_get/processor/ffmpeg.py
`-safe -1` set in #1029 in removed in ffmpeg 5.0: https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/46fb395952be32692385449ee214461603480b4b
=> change -safe to 0 for compatibility of ffmpeg5

src/you_get/extractors/bilibili.py
When download video consecutively, like ```you-get -I download.txt ...```, previous stream info is not clear, may cause download wrong video.
连续下载，例如使用-I模式时，前一个视频的信息未被清除，导致下载视频错误
=> clear stream info

README.md
- Adding the `pipenv` command option to let developers can install the `you-get` in the virtual Python environment. And it can let developers separate the environment  from default Python system environment easily :).
=> Add pipenv command usage option

src/you_get/common.py
Below exception was thrown when downloading a video with option --insecure.
The option `--insecure` was handled in the function `urlopen_with_retry` but not all `request.urlopen`, ie the function `get_response`.
The fix added the codes for ignoring ssl errors in the function `get_response` as well.
```
(venv) hong@GRAYSHEEP you-get %  cd /Users/hong/Desktop/Hong/git/you-get ; /usr/bin/env /Users/hong/Desktop/Hong/venv/bin/python3 /Users/hong/.vscode/extensions/ms-python.python-2021.5.926500501/pythonFiles/lib/python/debugpy/launcher 52084 -- you-get --debug --insecure -i -o download https://viu.tv/encore/we-are-the-littles/we-are-the-littlese1fong-hei-liu-paai-kau-mung 
[DEBUG] get_location: https://viu.tv/encore/we-are-the-littles/we-are-the-littlese1fong-hei-liu-paai-kau-mung
[DEBUG] …
```
=> fix for using insecure flag does not work

src/you_get/extractors/netease.py
`you-get` can only download the first 20 tracks in a radio list, so there's a need to traverse over pages to scrape all the tracks.
=> [netease]: Add pagination on netease radio

src/you_get/extractors/ixigua.py
`you-get -i --debug "https://www.ixigua.com/7114608501724283407?app=video_article&timestamp=1663582546&utm_medium=android&utm_campaign=client_share&utm_source=wechat_friend&test_group=v1"`
will traceback:
```
File "d:\setup\you-get\you-get", line 11, in <module>
File "D:\setup\you-get/src\you_get\__main__.py", line 92, in main
main(**kwargs)
File "D:\setup\you-get/src\you_get\common.py", line 1867, in main
script_main(any_download, any_download_playlist, **kwargs)
File "D:\setup\you-get/src\you_get\common.py", line 1759, in script_main
download_main(
File "D:\setup\you-get/src\you_get\common.py", line 1379, in download_main
download(url, **kwargs)
File "D:\setup\you-get/src\you_get\common.py", line 1858, in any_download …
```
=> [ixigua] fix 'string indices must be integers'

.github/workflows/python-package.yml
Python 3.11 will be on average ___22% faster___ than Python 3.10 so let’s give it a spin...
https://www.python.org/download/pre-releases
=> Add Python 3.11 release candidate 2 to the testing

src/you_get/extractors/douyin.py
Watermark is removed from videos at both left-top corner and the end of video.
=> [douyin] remove video watermark

src/you_get/extractors/bilibili.py
Support different codecs for bilibili now, especially for AV1, which cannot be fetched before.
See https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/videostream_url.md for details.
=> support different codecs for bilibili

src/you_get/extractors/bilibili.py
When there're more than single page videos in a collection, Download all videos as current code will only handle first page.
For 'space_channel_series' and 'space_channel_collection'
=> Download multipage video collection

README.md, setup.py
The README.md installation instructions failed for two reasons:
1. python 3.12 has removed the `imp` module and has replaced it by the `importlib` module. [1](https://docs.python.org/3/whatsnew/3.12.html#imp)
2. the use of setup.py as in the command `python setup.py install` is deprecated and should be replaced by the recommended way of `python -m pip install path/to/project`. [2](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/)
BTW, the reason why I changed `python3` to `python` is because (1) this should be the mainstream nowadays, and (2) I don't know since when win10 has one `python3.exe` under `%APPDATA%\Local\Microsoft\WindowsApps\` which is non-functional. (At the same time the python 3.12 official release no longer comes with a `python3.exe`.) (Thus calling …
=> fix the outdated installation instructions

src/you_get/extractors/bilibili.py
Hi! Looks like `comment.bilibili.com` requires headers now. I encountered a problem like this:
```
$ you-get --debug -c /app/cookies.txt -l -i https://www.bilibili.com/video/BV1gt421A7Mz/
[DEBUG] get_content: https://www.bilibili.com/video/BV1gt421A7Mz/
[DEBUG] get_content: https://www.bilibili.com/video/av1753632765?p=1
[DEBUG] get_content: https://www.bilibili.com/video/av1753632765?p=1
[DEBUG] get_content: https://api.bilibili.com/x/player/playurl?avid=1753632765&cid=1517599397&qn=64&type=&otype=json&fnver=0&fnval=16&fourk=1
[DEBUG] get_content: https://api.bilibili.com/x/player/playurl?avid=1753632765&cid=1517599397&qn=32&type=&otype=json&fnver=0&fnval=16&fourk=1
[DEBUG] get_content: https://api.bilibili.com/x/player/playurl?avid=1753632765&cid=1517599397&qn=16&type=&otype=json&fnver=0 …
```
=> fix: [extractors.bilibili] add headers when requesting for danmaku

.github/workflows/python-package.yml, setup.py, you-get.json
should pass the checks now... setuptools needs to be upgraded for python 3.12 test to find the module
edit:
still cannot pass unittest... but anyway, failures seemed to be merely network issues...
plus, one may consider migrate from `make test` `python3 setup.py test` unittest to the modern way `pytest tests` (start by having two ways of test in workflow yaml), see [1](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#what-about-other-commands), [2](https://docs.pytest.org/en/latest/how-to/unittest.html)
=> Add workflow test on python 3.12

setup.py, src/you_get/extractors/youtube.py, tests/test.py
Decrypting `signatureCipher` to fix the recent 403 error, as well as to solve the long-standing download speed throttling issue (#2950). This was made possible thanks to the lightweight JavaScript interpreter [dukpy](https://pypi.org/project/dukpy/).
=> [YouTube] Fix 403 error and throttling

src/you_get/extractors/youtube.py
Today I have tried use you-get to download video from YouTube. I noticed one of my hosts from OVH Cloud FR failed to download the example video:
```sh
(venv) ubuntu@fr1:/tmp$ you-get "https://www.youtube.com/watch?v=jNQXAC9IVRw" --debug
[DEBUG] Extracting from the video page...
[DEBUG] get_content: https://www.youtube.com/watch?v=jNQXAC9IVRw
[DEBUG] Retrieving the player code...
[DEBUG] get_content: https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/fr_FR/base.js
[DEBUG] Loading ytInitialPlayerResponse...
you-get: version 0.4.1718, a tiny downloader that scrapes the web.
you-get: Namespace(version=False, help=False, info=False, url=False, json=False, no_merge=False, no_caption=False, postfix=False, prefix=None, force=False, skip_existing_file_size_check=False, format=None, …
```
=> Add ytInitialPlayerResponse checker to let user easily know problem

README.md
`you-get` is available and working on Flox today.
I tested it out as follows.
```console
$ flox init
✨ Created environment 'tmp.nmbKH8f71c' (aarch64-darwin)
Next:
$ flox search <package>    <- Search for a package
$ flox install <package>   <- Install a package into an environment
$ flox activate            <- Enter the environment
$ flox edit                <- Add environment variables and shell hooks
$ flox install you-get
✅ 'you-get' installed to environment 'tmp.nmbKH8f71c'
$ flox activate -- you-get --version
you-get: version 0.4.1700, a tiny downloader that scrapes the web.
```
=> Add Flox as an installation option

src/you_get/extractors/miaopai.py
The -o parameter, used for specifying output filename, was not functioning correctly when downloading videos from Miaopai. This commit addresses the issue and ensures the parameter works as intended.
=> Fix: Restore functionality of -o parameter for Miaopai downloads
